/*
  STEFANOV VODIČ – podaci o lokacijama
  ------------------------------------
  Mesta su uvezena iz tvojih Google Maps recenzija (Google Takeout, Reviews.json):
  samo Beograd, samo ocene 4 i 5, bez servisa i prodavnica.
  Slobodno menjaj, dodaj ili obriši bilo koje mesto. Svako mesto je jedan objekat.

  Polja:
    id          jedinstveni kratki naziv, bez razmaka (npr. "kalemegdan")
    name        naziv mesta
    category    jedna od: "jelo", "kafa", "pice", "vidi", "radi", "noc"
    area        kraj grada (npr. "Dorćol", "Zemun", "Vračar")
    image       (opciono) putanja do tvoje slike u folderu images/ (npr. "images/kalemegdan.jpg")
                ako je prazno, sajt uzima fotografiju sa Google Maps (potreban ključ)
    short       (opciono) jedna rečenica o mestu
    description (opciono) duži opis u detaljima
    tip         (opciono) poseban Stefanov savet
    rating      ocena sa Google Maps (1 do 5); sa Google ključem sajt prikazuje Google prosek i broj recenzija
    date        datum recenzije
    price       "€", "€€", "€€€" ili "" ako nije poznato
    address     adresa
    lat, lng    koordinate
    mapsUrl     link ka mestu na Google Maps
    tags        lista kratkih oznaka
    icon        (opciono) ilustracija za pin i poster (npr. "🎭")
    source      "predlog" za mesta koja nisu iz tvojih recenzija
    placeId     (opciono) Google Place ID, ako Google nađe pogrešnu fotografiju
*/

const CATEGORIES = {
  jelo: { label: "Jelo", icon: "🍽️" },
  kafa: { label: "Kafa i slatko", icon: "☕" },
  pice: { label: "Piće", icon: "🍸" },
  vidi: { label: "Vidi", icon: "🏛️" },
  radi: { label: "Aktivnosti", icon: "🎟️" },
  noc: { label: "Noćni život", icon: "🌙" },
};

const LOCATIONS = [
  {
    "id": "popy-coffee-family",
    "name": "Popy Coffee Family",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-10-03",
    "price": "",
    "address": "Cara Lazara 16, Beograd 11000",
    "lat": 44.817913,
    "lng": 20.45455,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfa42cf36daf1f01b",
    "tags": []
  },
  {
    "id": "paninoteca",
    "name": "Paninoteca",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-09-29",
    "price": "€€",
    "address": "Kneginje Ljubice 32, Beograd 11000",
    "lat": 44.821629,
    "lng": 20.464106,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1af26373f02cbdf7",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "peak-place",
    "name": "Peak Place",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-09-09",
    "price": "",
    "address": "Bulevar Zorana Đinđića, Beograd",
    "lat": 44.812617,
    "lng": 20.429756,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x16d2ecb35895d6e3",
    "tags": []
  },
  {
    "id": "pomodoro-nuovo",
    "name": "Pomodoro Nuovo",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-08-28",
    "price": "",
    "address": "Bulevar Mihajla Pupina 115, Beograd 11070",
    "lat": 44.816997,
    "lng": 20.428393,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5c5ec880bdf0aeb5",
    "tags": []
  },
  {
    "id": "cetiri-coffee-bar",
    "name": "Cetiri coffee bar",
    "category": "kafa",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-08-23",
    "price": "",
    "address": "Terazije 36, Beograd 11000",
    "lat": 44.811433,
    "lng": 20.461696,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xab606969b6f61ab",
    "tags": []
  },
  {
    "id": "ciklo-bar",
    "name": "Ciklo Bar",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-06-20",
    "price": "€",
    "address": "Milentija Popovića 20, Beograd 11000",
    "lat": 44.810798,
    "lng": 20.429426,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb014e2b3dc883a38",
    "tags": []
  },
  {
    "id": "og-kebab",
    "name": "OG Kebab",
    "category": "jelo",
    "area": "Zvezdara",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-06-13",
    "price": "",
    "address": "Bulevar kralja Aleksandra 210, Beograd 11000",
    "lat": 44.799507,
    "lng": 20.489031,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3dd422fc9b797ba3",
    "tags": []
  },
  {
    "id": "gradska-przionica",
    "name": "Gradska Pržionica",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-06-13",
    "price": "",
    "address": "Dunavski kej 46, Beograd",
    "lat": 44.827493,
    "lng": 20.471522,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xef5dbc86abbdfb78",
    "tags": []
  },
  {
    "id": "loch-ness-belgrade",
    "name": "Loch Ness Belgrade",
    "category": "jelo",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-06-10",
    "price": "",
    "address": "Ada Ciganlija 65, Beograd",
    "lat": 44.777003,
    "lng": 20.376701,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x61e49676909c568f",
    "tags": []
  },
  {
    "id": "turbomax-karting-centar",
    "name": "Turbomax Karting centar",
    "category": "radi",
    "area": "Višnjica",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-05-20",
    "price": "",
    "address": "Pančevački Put 81, Beograd 11210",
    "lat": 44.852447,
    "lng": 20.52921,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x64e8d33549345571",
    "tags": []
  },
  {
    "id": "tivoli-pizza",
    "name": "Tivoli Pizza",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-05-19",
    "price": "",
    "address": "Nedeljka Gvozdenovića 22a, Beograd",
    "lat": 44.812482,
    "lng": 20.370579,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x20fccb7ea3825f56",
    "tags": []
  },
  {
    "id": "da-luca-pizzeria-due-restaurant",
    "name": "Da Luca Pizzeria Due Restaurant",
    "category": "jelo",
    "area": "Višnjica",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-05-15",
    "price": "€€",
    "address": "Pančevački Put 56, Beograd 11060",
    "lat": 44.847496,
    "lng": 20.523397,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc0886ae104e115c1",
    "tags": []
  },
  {
    "id": "stories",
    "name": "Stories",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-05-11",
    "price": "€€",
    "address": "Pjarona De Mondezira 28, Beograd 11000",
    "lat": 44.823209,
    "lng": 20.455568,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf66df3dbb28b0fbd",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "bistro-kezual",
    "name": "Bistro KEŽUAL",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-28",
    "price": "",
    "address": "34 RS 11000, Beograd 11000",
    "lat": 44.799409,
    "lng": 20.480587,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x2b538be736e05736",
    "tags": []
  },
  {
    "id": "ustipak-bar-vracar",
    "name": "Uštipak bar Vračar",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-28",
    "price": "€",
    "address": "Njegoševa BB, Kalenić pijaca lokal 28, Beograd",
    "lat": 44.799798,
    "lng": 20.475379,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd17047fb5b7de04d",
    "tags": [
      "doručak"
    ]
  },
  {
    "id": "meduza",
    "name": "Meduza",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-26",
    "price": "",
    "address": "Gospodar-Jevremova 6, Beograd 11000",
    "lat": 44.822326,
    "lng": 20.456348,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1247acabfa35dc64",
    "tags": []
  },
  {
    "id": "muzej-paranormalnog",
    "name": "Muzej paranormalnog",
    "category": "vidi",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-24",
    "price": "",
    "address": "Zmaj Jovina 4, Beograd 11000",
    "lat": 44.816657,
    "lng": 20.457068,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb0246e61d60c2fef",
    "tags": []
  },
  {
    "id": "punch-ramen-belgrade",
    "name": "PUNCH RAMEN BELGRADE",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-23",
    "price": "€€",
    "address": "1 floor, Maršala Birjuzova 2-4, Beograd 11000",
    "lat": 44.814368,
    "lng": 20.459091,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb8717439f4d6e2ce",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "kineski-fast-food-good-appetite",
    "name": "Kineski fast food Good Appetite",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-22",
    "price": "",
    "address": "Vase Čarapića 7, Beograd 11000",
    "lat": 44.817592,
    "lng": 20.45906,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x77683554313465ed",
    "tags": []
  },
  {
    "id": "pivokratija-2",
    "name": "Pivokratija 2",
    "category": "pice",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-20",
    "price": "",
    "address": "Savski nasip bb, Beograd 11070",
    "lat": 44.800813,
    "lng": 20.417473,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x76bc2ea769c13bf4",
    "tags": []
  },
  {
    "id": "zavicaj-ada",
    "name": "Zavičaj Ada",
    "category": "jelo",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-11",
    "price": "",
    "address": "Unnamed Rd, Beograd",
    "lat": 44.789169,
    "lng": 20.404013,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x2b72b98f2980eb3e",
    "tags": []
  },
  {
    "id": "sonder-gastrosor",
    "name": "Sonder Gastrošor",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-06",
    "price": "",
    "address": "Žorža Klemansoa 27v, Beograd 11000",
    "lat": 44.824821,
    "lng": 20.470733,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9596ed10da62e142",
    "tags": []
  },
  {
    "id": "fitbar",
    "name": "FitBar",
    "category": "jelo",
    "area": "Zvezdara",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-02",
    "price": "€€",
    "address": "Kajmakčalanska 22, Beograd",
    "lat": 44.798535,
    "lng": 20.487825,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5aaa7d5262c15571",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "restaurant-manifest",
    "name": "Restaurant “Manifest”",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-11",
    "price": "€€",
    "address": "Jurija Gagarina 12, Beograd 11070",
    "lat": 44.804704,
    "lng": 20.412178,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8480b293f2e410d2",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "buratina-bar",
    "name": "BURATINA Bar",
    "category": "pice",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-07",
    "price": "",
    "address": "Svetogorska 46, Beograd 11103",
    "lat": 44.812783,
    "lng": 20.469915,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x64e5baa7cfacbf04",
    "tags": []
  },
  {
    "id": "cin-cin",
    "name": "Čin Čin",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-06",
    "price": "€",
    "address": "Radoslava Grujića 28, Beograd 11000",
    "lat": 44.800793,
    "lng": 20.480795,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb4ae30d45282838a",
    "tags": []
  },
  {
    "id": "eje-belgrade",
    "name": "EJE Belgrade",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-06",
    "price": "",
    "address": "Dobračina 39, Beograd 11000",
    "lat": 44.820638,
    "lng": 20.463911,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x39b927b7bc3bad42",
    "tags": []
  },
  {
    "id": "super-vok",
    "name": "Super Vok",
    "category": "jelo",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-01",
    "price": "€",
    "address": "Terazije 7-9, Beograd",
    "lat": 44.81416,
    "lng": 20.460757,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd1d7ad5b0c7a8b76",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "strogi-centar",
    "name": "Strogi Centar",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-02-16",
    "price": "€",
    "address": "Gospodar-Jevremova 43, Beograd 11000",
    "lat": 44.819706,
    "lng": 20.461641,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8a446fb61f12cdfe",
    "tags": []
  },
  {
    "id": "crveni-petao",
    "name": "Crveni Petao",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-02-02",
    "price": "",
    "address": "Cara Lazara 16, Beograd",
    "lat": 44.81772,
    "lng": 20.454579,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x69895e5ce7c4308e",
    "tags": []
  },
  {
    "id": "dogma-brewery-tap-room",
    "name": "Dogma Brewery & Tap Room",
    "category": "pice",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-01-31",
    "price": "",
    "address": "Radnička 3 Čukarica Belgrade, 11030",
    "lat": 44.788478,
    "lng": 20.423116,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa14f065b87591bc6",
    "tags": []
  },
  {
    "id": "perlo-burgeri",
    "name": "Perlo burgeri",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-01-17",
    "price": "",
    "address": "Đure Jakšića br. 3, Beograd 11000",
    "lat": 44.817439,
    "lng": 20.456614,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x632850d20984f50c",
    "tags": []
  },
  {
    "id": "mamagayo",
    "name": "Mamagayo",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-01-13",
    "price": "€€",
    "address": "Aleksinačkih Rudara bb, Beograd 11070",
    "lat": 44.827792,
    "lng": 20.412803,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x81710658bb173682",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "d59b-belgrade",
    "name": "D59B | Belgrade",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-01-02",
    "price": "€",
    "address": "Kralja Petra 70, Beograd",
    "lat": 44.821811,
    "lng": 20.458358,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x17ec36690ab655b1",
    "tags": []
  },
  {
    "id": "avocado-belvil",
    "name": "Avocado Belvil",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-30",
    "price": "",
    "address": "Đorđa Stanojevića 9b, Beograd 11070",
    "lat": 44.806678,
    "lng": 20.406826,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x26e76dbc61b2240d",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "mali-hram",
    "name": "Mali Hram",
    "category": "vidi",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-26",
    "price": "",
    "address": "Hilandarska 24, Beograd",
    "lat": 44.81507,
    "lng": 20.468653,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9543f93f2076c9c7",
    "tags": []
  },
  {
    "id": "badger-mug",
    "name": "Badger & Mug",
    "category": "pice",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-20",
    "price": "",
    "address": "Nušićeva 6, Beograd 11102",
    "lat": 44.813799,
    "lng": 20.461656,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf1106025125cec59",
    "tags": []
  },
  {
    "id": "liga-pub-obilicev-venac",
    "name": "Liga Pub Obilicev venac",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-20",
    "price": "",
    "address": "Obilićev venac 29, Beograd 11000",
    "lat": 44.815627,
    "lng": 20.459072,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x43d0bbeb78672d10",
    "tags": []
  },
  {
    "id": "espresso-bar",
    "name": "Espresso bar",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-20",
    "price": "",
    "address": "Topličin venac 7, Beograd 11000",
    "lat": 44.816168,
    "lng": 20.45589,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7d9ec2d26e02ecc4",
    "tags": []
  },
  {
    "id": "shootiranje-novi-beograd",
    "name": "Shootiranje Novi Beograd",
    "category": "noc",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-14",
    "price": "",
    "address": "Tošin bunar 162, Beograd 11000",
    "lat": 44.828533,
    "lng": 20.398378,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8a28e76724fd7fbc",
    "tags": []
  },
  {
    "id": "st-mark-s-place",
    "name": "St. Mark's Place",
    "category": "jelo",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-07",
    "price": "",
    "address": "Bulevar kralja Aleksandra 17, Beograd",
    "lat": 44.809769,
    "lng": 20.467852,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7269b22bdccb3f6a",
    "tags": []
  },
  {
    "id": "ugao-specialty-coffee",
    "name": "UGAO Specialty Coffee",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-06",
    "price": "€",
    "address": "Dunavska 2i, Beograd 11000",
    "lat": 44.828572,
    "lng": 20.45257,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa6490bbdd93ee18d",
    "tags": []
  },
  {
    "id": "sloj-bistro-bakery-waterfront",
    "name": "SLOJ bistro & bakery WATERFRONT",
    "category": "kafa",
    "area": "Beograd na vodi",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-06",
    "price": "",
    "address": "Bulevar Vudroa Vilsona 8V, Beograd 11000",
    "lat": 44.80564,
    "lng": 20.450985,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x31888f49f5a6bf26",
    "tags": []
  },
  {
    "id": "cafe-934",
    "name": "Cafe 9¾",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-03",
    "price": "",
    "address": "Dunavska 2a, Beograd 11000",
    "lat": 44.828322,
    "lng": 20.454708,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x66a26851fb4acd63",
    "tags": []
  },
  {
    "id": "lefer-splav",
    "name": "LeFer Splav",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-22",
    "price": "",
    "address": "Gandijeva BB, Beograd 11070",
    "lat": 44.795358,
    "lng": 20.392997,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe259a7cc9ede5ba1",
    "tags": []
  },
  {
    "id": "green-restaurant",
    "name": "Green Restaurant",
    "category": "jelo",
    "area": "Beograd na vodi",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-15",
    "price": "",
    "address": "Savska 20, Beograd 11000",
    "lat": 44.805175,
    "lng": 20.453327,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfdb1607a86dfde5a",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "tokar-kafeterija",
    "name": "Tokar Kafeterija",
    "category": "kafa",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-15",
    "price": "",
    "address": "Kneza Danila 9, Beograd 11000",
    "lat": 44.810777,
    "lng": 20.476648,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3bfde72cf773163f",
    "tags": []
  },
  {
    "id": "bistro-tri",
    "name": "Bistro Tri",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-09",
    "price": "€",
    "address": "Mileševska 16, Beograd 11000",
    "lat": 44.800653,
    "lng": 20.477805,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xcfd2454f26e451ec",
    "tags": []
  },
  {
    "id": "pane-e-vino-west-65",
    "name": "Pane E Vino, WEST 65",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-27",
    "price": "",
    "address": "Omladinskih brigada 86i, Beograd",
    "lat": 44.812502,
    "lng": 20.399729,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x21f7a4b9b05cadd4",
    "tags": []
  },
  {
    "id": "monk-s-bar",
    "name": "Monk's Bar",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-26",
    "price": "",
    "address": "71 KNJEGINJE ZORKE, 11104, Belgrade (Vracar), Belgrade county",
    "lat": 44.803306,
    "lng": 20.472181,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xeb8098b405f280ff",
    "tags": []
  },
  {
    "id": "velika-skadarlija-restaurant",
    "name": "Velika Skadarlija restaurant",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-10",
    "price": "€€€",
    "address": "Skadarska 40d, Beograd",
    "lat": 44.818687,
    "lng": 20.466337,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xff2b548f5e8f2adf",
    "tags": []
  },
  {
    "id": "giovanni-s-pizzeria",
    "name": "Giovanni's Pizzeria",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-07",
    "price": "€€€",
    "address": "Gračanička 11, Beograd 11000",
    "lat": 44.817795,
    "lng": 20.454405,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x94263cf6190f1141",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "fresca",
    "name": "Fresca",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-07",
    "price": "",
    "address": "Dobračina 29a, Beograd 11000",
    "lat": 44.819836,
    "lng": 20.462848,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x19092e5aa34fe9eb",
    "tags": []
  },
  {
    "id": "im-camy-lunch-bar",
    "name": "i’m Camy Lunch Bar",
    "category": "kafa",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-28",
    "price": "€",
    "address": "Pavla Vuisića 69 B, Beograd 11080",
    "lat": 44.853065,
    "lng": 20.347089,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8a87febe437edaf0",
    "tags": [
      "doručak"
    ]
  },
  {
    "id": "piatakia-new-belgrade",
    "name": "Piatakia , New Belgrade",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-24",
    "price": "€€€",
    "address": "Bulevar Arsenija Čarnojevića 54, Beograd",
    "lat": 44.811867,
    "lng": 20.424421,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9270763c651a466",
    "tags": []
  },
  {
    "id": "passengers-bar",
    "name": "Passengers Bar",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-24",
    "price": "",
    "address": "Simina 5, Beograd 11000",
    "lat": 44.820333,
    "lng": 20.459081,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x68b262c958d11bb4",
    "tags": []
  },
  {
    "id": "restoran-plato",
    "name": "Restoran PLATO",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-24",
    "price": "",
    "address": "Čika-Ljubina 18-20, Beograd 11000",
    "lat": 44.818204,
    "lng": 20.458081,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe838bfc05147410d",
    "tags": []
  },
  {
    "id": "sava-45-event-center",
    "name": "Sava 45 event center",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-21",
    "price": "",
    "address": "Savski kej 83, Beograd 11070",
    "lat": 44.793736,
    "lng": 20.382812,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb8cad03faec8929a",
    "tags": []
  },
  {
    "id": "rizoto-bar",
    "name": "Rizoto bar",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-20",
    "price": "€",
    "address": "Katanićeva 18, Beograd 11000",
    "lat": 44.799378,
    "lng": 20.469693,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbca7bc098592ecd0",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "poslasticarnica-kostana",
    "name": "Poslastičarnica Koštana",
    "category": "kafa",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-19",
    "price": "",
    "address": "Bulevar kralja Aleksandra 93, Beograd 11000",
    "lat": 44.802456,
    "lng": 20.483041,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6332da8dd86055c2",
    "tags": []
  },
  {
    "id": "the-risotto-bar",
    "name": "The Risotto Bar",
    "category": "jelo",
    "area": "Zvezdara",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-19",
    "price": "",
    "address": "Bulevar kralja Aleksandra 115, Beograd 11000",
    "lat": 44.801543,
    "lng": 20.48524,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5a6d56cd2b2e83a5",
    "tags": []
  },
  {
    "id": "leposava-bar",
    "name": "Leposava bar",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-13",
    "price": "€",
    "address": "Velike stepenice 6, Beograd 11000",
    "lat": 44.818462,
    "lng": 20.450372,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc9b0fe53e9684",
    "tags": []
  },
  {
    "id": "ciribu-ciriba",
    "name": "Ćiribu Ćiriba",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-11",
    "price": "€€",
    "address": "Masarikov trg 6, Beograd 11080",
    "lat": 44.844229,
    "lng": 20.415132,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbf2a0a9aee87ab0",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "between-espresso-wine-bar",
    "name": "Between Espresso & Wine Bar",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-10",
    "price": "€",
    "address": "Strahinjića Bana 59, Beograd 11158",
    "lat": 44.820827,
    "lng": 20.463153,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfa6d8bb183fe4c5",
    "tags": []
  },
  {
    "id": "brekky",
    "name": "Brekky",
    "category": "kafa",
    "area": "Beograd na vodi",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-05",
    "price": "",
    "address": "Bulevar Vudroa Vilsona 10, Beograd 11000",
    "lat": 44.805174,
    "lng": 20.45062,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf0cfab259cf8115c",
    "tags": []
  },
  {
    "id": "black-george",
    "name": "BLACK GEORGE",
    "category": "pice",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-04",
    "price": "",
    "address": "Karađorđeva 65, Beograd 11000",
    "lat": 44.812516,
    "lng": 20.45338,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb10330456c0d5b7d",
    "tags": []
  },
  {
    "id": "beishanlan-bubble-tea",
    "name": "Beishanlan Bubble Tea",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-02",
    "price": "",
    "address": "Serbia, Beograd, Maršala Birjuzova, RS 贝尔格莱德 Maršala Birjuzova 1, Beograd 11000邮政编码: 11000",
    "lat": 44.814275,
    "lng": 20.45887,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x274418b5e34fff6a",
    "tags": []
  },
  {
    "id": "sushi-xo-novi-beograd",
    "name": "Sushi XO Novi Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-02",
    "price": "€€",
    "address": "Jurija Gagarina 14d, Beograd 11070",
    "lat": 44.805532,
    "lng": 20.409548,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3ac1194c125c2b24",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "bobo-boucher-et-botanist",
    "name": "Bobo Boucher et Botanist",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-24",
    "price": "",
    "address": "Sinđelićeva 3a, Beograd 11000",
    "lat": 44.802625,
    "lng": 20.479309,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7eaa5669b98b0d86",
    "tags": []
  },
  {
    "id": "kafeterija-mlin-novi-beograd",
    "name": "Kafeterija Mlin Novi Beograd",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-23",
    "price": "€",
    "address": "Španskih boraca 3, Beograd 11000",
    "lat": 44.818622,
    "lng": 20.424067,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xab86a45d539d5c92",
    "tags": []
  },
  {
    "id": "taurunum-pogled-pizza-bar",
    "name": "Taurunum Pogled Pizza Bar",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-22",
    "price": "€€",
    "address": "Sinđelićeva 30, Beograd",
    "lat": 44.848729,
    "lng": 20.411024,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe7cf7cef088cf301",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "ca-ca-fe",
    "name": "ca.ca.fe",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-21",
    "price": "€",
    "address": "Narodnih heroja 41, Beograd 11070",
    "lat": 44.820481,
    "lng": 20.405185,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x42280493d513360a",
    "tags": []
  },
  {
    "id": "bure-piva",
    "name": "Bure Piva",
    "category": "pice",
    "area": "Konjarnik",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-09",
    "price": "",
    "address": "Živka Davidovića 89, Beograd 11000",
    "lat": 44.786789,
    "lng": 20.514824,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x4f261ec772e7121",
    "tags": []
  },
  {
    "id": "adam-stroopwafel",
    "name": "A’dam Stroopwafel",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-05",
    "price": "",
    "address": "Nikole Spasića 3, Beograd 11000",
    "lat": 44.818262,
    "lng": 20.45454,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf46edfa4d42f4c45",
    "tags": []
  },
  {
    "id": "predji-preko",
    "name": "Pređi preko",
    "category": "jelo",
    "area": "Borča",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-07-05",
    "price": "",
    "address": "Lazara Dokica 97, Borča",
    "lat": 44.852011,
    "lng": 20.421186,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf298e5665ec7519",
    "tags": []
  },
  {
    "id": "tattoo-bar-belgrade",
    "name": "Tattoo Bar Belgrade",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-26",
    "price": "€€",
    "address": "Venizelosova 29T, Beograd 11108",
    "lat": 44.820151,
    "lng": 20.473016,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa04171a13a6ead2a",
    "tags": []
  },
  {
    "id": "bunny-cafe-belgrade",
    "name": "Bunny cafe Belgrade",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-18",
    "price": "",
    "address": "Skenderbegova 53b, Beograd",
    "lat": 44.821325,
    "lng": 20.465787,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfc68bbab9165804a",
    "tags": []
  },
  {
    "id": "che-gusto-beograd",
    "name": "Che Gusto - Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-13",
    "price": "",
    "address": "Omladinskih brigada 90D, Beograd 11070",
    "lat": 44.813146,
    "lng": 20.395629,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1dbe2e2bce41703c",
    "tags": []
  },
  {
    "id": "reka",
    "name": "Reka",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-13",
    "price": "",
    "address": "Kej Oslobođenja 73b, Beograd",
    "lat": 44.849175,
    "lng": 20.41131,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe6df800114d2c616",
    "tags": []
  },
  {
    "id": "alisa",
    "name": "Alisa",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-05",
    "price": "",
    "address": "Kralja Milutina 35, Beograd",
    "lat": 44.803867,
    "lng": 20.46622,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8d295946b169cc68",
    "tags": []
  },
  {
    "id": "dot-coffee-bar",
    "name": "DOT COFFEE | BAR",
    "category": "kafa",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-05",
    "price": "",
    "address": "Čumićevo sokače lokal 120, Beograd 11000",
    "lat": 44.814741,
    "lng": 20.461634,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3bd95ac6e4db7f2b",
    "tags": []
  },
  {
    "id": "noble-roots-cocktail-bar",
    "name": "Noble Roots Cocktail Bar",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-05",
    "price": "€€€",
    "address": "Dositejeva 7, Beograd 11000",
    "lat": 44.817319,
    "lng": 20.460977,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x67a87d42d8172f82",
    "tags": []
  },
  {
    "id": "smokvica-jovanova",
    "name": "Smokvica Jovanova",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-03",
    "price": "",
    "address": "Gospodar Jovanova 45a, 11000, Beograd",
    "lat": 44.820977,
    "lng": 20.461002,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9d5855fae724b2b0",
    "tags": []
  },
  {
    "id": "pizzeria-trg",
    "name": "Pizzeria Trg",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-02",
    "price": "",
    "address": "Makedonska 5, Beograd 11103",
    "lat": 44.815894,
    "lng": 20.461762,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc9d60d11d23da373",
    "tags": []
  },
  {
    "id": "wagokoro",
    "name": "Wagokoro",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-02",
    "price": "",
    "address": "Carigradska 10, Beograd 11000",
    "lat": 44.817632,
    "lng": 20.472544,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd4f2df3c55846671",
    "tags": []
  },
  {
    "id": "botako-restoran-dorcol-picerija-dostava",
    "name": "Botako Restoran Dorćol | Picerija & Dostava",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-02",
    "price": "€€",
    "address": "Šantićeva 8, Beograd 11000",
    "lat": 44.819077,
    "lng": 20.471077,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb895fe5e8be2220",
    "tags": []
  },
  {
    "id": "basic-coffee-breakfast",
    "name": "BASIC coffee & breakfast",
    "category": "kafa",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-30",
    "price": "€",
    "address": "Admirala Geprata 10, Beograd 11000",
    "lat": 44.80796,
    "lng": 20.460005,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x53f8f95af636cb95",
    "tags": [
      "brunch"
    ]
  },
  {
    "id": "polapola-bar",
    "name": "PolaPola Bar",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-28",
    "price": "",
    "address": "Žorža Klemansoa 29b, Beograd",
    "lat": 44.825283,
    "lng": 20.470529,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x517b6ac78e5cd8dc",
    "tags": []
  },
  {
    "id": "8-bar",
    "name": "8 Bar",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-28",
    "price": "€€",
    "address": "Gastrošor, Žorža Klemansoa 27v, Beograd 11158",
    "lat": 44.825212,
    "lng": 20.470582,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x75516d21dd0b7dd5",
    "tags": []
  },
  {
    "id": "fenisa",
    "name": "Fenisa",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-26",
    "price": "€",
    "address": "Kneginje Zorke 8, Beograd 11000",
    "lat": 44.800064,
    "lng": 20.466792,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb91dba5c37c0b510",
    "tags": []
  },
  {
    "id": "mali-prag",
    "name": "Mali prag",
    "category": "pice",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-17",
    "price": "€",
    "address": "Kraljice Natalije 50, Beograd 11000",
    "lat": 44.810887,
    "lng": 20.459401,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe82eade193631bbd",
    "tags": []
  },
  {
    "id": "big-padel",
    "name": "Big Padel",
    "category": "radi",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-10",
    "price": "",
    "address": "Savski nasip, Beograd 11070",
    "lat": 44.79851,
    "lng": 20.417576,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7c1cc6aac104b74b",
    "tags": []
  },
  {
    "id": "lola-restoran",
    "name": "Lola Restoran",
    "category": "jelo",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-10",
    "price": "",
    "address": "Ada Ciganlija 2, Beograd 11000",
    "lat": 44.792882,
    "lng": 20.408375,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe2511b7c02b7fefb",
    "tags": []
  },
  {
    "id": "the-view-rooftop",
    "name": "The View Rooftop",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "",
    "address": "Internacionalnih brigada 9, Beograd 11000",
    "lat": 44.795454,
    "lng": 20.467577,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa55538a8a98057e7",
    "tags": []
  },
  {
    "id": "trandafilovic",
    "name": "Trandafilović",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "",
    "address": "Makenzijeva 73, Beograd 11000",
    "lat": 44.798998,
    "lng": 20.472815,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc83e87b7b2731d9e",
    "tags": []
  },
  {
    "id": "diner-bros-novi-beograd",
    "name": "Diner Bros. Novi Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "€€",
    "address": "Jurija Gagarina 19, Beograd 11073",
    "lat": 44.803466,
    "lng": 20.409728,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5e0db7008862122e",
    "tags": []
  },
  {
    "id": "lastavica-caffe",
    "name": "Lastavica caffe",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "",
    "address": "Jurija Gagarina 21, Beograd 11070",
    "lat": 44.80352,
    "lng": 20.408194,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbdbc2851c3e2b094",
    "tags": []
  },
  {
    "id": "rocket-coffee",
    "name": "Rocket Coffee",
    "category": "kafa",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-06",
    "price": "",
    "address": "Karađorđeva 49, Beograd 11000",
    "lat": 44.814197,
    "lng": 20.451717,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5ed8d12ad5c3b1d6",
    "tags": []
  },
  {
    "id": "kissa10",
    "name": "Kissa10",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-04",
    "price": "€€",
    "address": "Dobračina 29, Beograd",
    "lat": 44.819894,
    "lng": 20.462942,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7830b4c2b850371a",
    "tags": []
  },
  {
    "id": "3d-board-game-pub",
    "name": "3D Board Game Pub",
    "category": "radi",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-27",
    "price": "",
    "address": "Palmira Toljatija 5, Beograd 11000",
    "lat": 44.829336,
    "lng": 20.411956,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb20cf7411ad16c03",
    "tags": []
  },
  {
    "id": "pinecone-bar-theater",
    "name": "Pinecone Bar & Theater",
    "category": "noc",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-27",
    "price": "€€",
    "address": "Vladete Jerotića 5, Beograd 11101",
    "lat": 44.814995,
    "lng": 20.471743,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x30a8bb16f98563a5",
    "tags": []
  },
  {
    "id": "bife-bar",
    "name": "Bife bar",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-25",
    "price": "",
    "address": "Maršala Birjuzova 2-4, Beograd 11000",
    "lat": 44.814502,
    "lng": 20.459093,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x2a82164656f0a61b",
    "tags": []
  },
  {
    "id": "di-napoli-pizzeria-restaurant",
    "name": "Di Napoli - Pizzeria Restaurant",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-23",
    "price": "",
    "address": "Bulevar Zorana Đinđića 12E, Beograd 11070",
    "lat": 44.81303,
    "lng": 20.428896,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb97671acd4608ea2",
    "tags": []
  },
  {
    "id": "gelato-bar",
    "name": "Gelato Bar",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-22",
    "price": "",
    "address": "Jurija Gagarina 28, Beograd",
    "lat": 44.803963,
    "lng": 20.388352,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbabfe587daf2e5e0",
    "tags": []
  },
  {
    "id": "helga-s-pub-mesi-mesi",
    "name": "Helga's Pub Mesi Mesi",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-22",
    "price": "",
    "address": "Jurija Gagarina 28a, Beograd 11070",
    "lat": 44.803923,
    "lng": 20.388201,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x434e4511a5dc9283",
    "tags": []
  },
  {
    "id": "the-pijaca-2",
    "name": "The Pijaca 2",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-22",
    "price": "",
    "address": "Vajara Živojna Lukića 62, Beograd 11070",
    "lat": 44.820426,
    "lng": 20.393712,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x68264a95d8c7df34",
    "tags": []
  },
  {
    "id": "vukov-bozicni-kutak",
    "name": "Vukov Božićni kutak",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-17",
    "price": "€",
    "address": "Nikole Spasića 2a, Beograd",
    "lat": 44.818632,
    "lng": 20.454694,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xadc1fb6a13f02a3f",
    "tags": []
  },
  {
    "id": "billys-pizza-tavern-dorcol",
    "name": "Billy’s Pizza Tavern Dorćol",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-17",
    "price": "€€",
    "address": "Gospodar Jovanova 56, Beograd",
    "lat": 44.819253,
    "lng": 20.463513,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5b6e8891cb42fbad",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "dolly-bell",
    "name": "Dolly Bell",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-12",
    "price": "",
    "address": "Bulevar Mihajla Pupina 165b, Beograd 11070",
    "lat": 44.821557,
    "lng": 20.414782,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x69a30b62d217709c",
    "tags": []
  },
  {
    "id": "museum-of-contemporary-art",
    "name": "Museum of contemporary art",
    "category": "vidi",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-12",
    "price": "",
    "address": "Ušće 10, block 15, 11070, Ušće 10, Beograd",
    "lat": 44.819584,
    "lng": 20.442477,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd676a195f8f19372",
    "tags": []
  },
  {
    "id": "pizzeria-square",
    "name": "Pizzeria Square",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-12",
    "price": "€",
    "address": "Venizelosova 11, Beograd 11000",
    "lat": 44.8203,
    "lng": 20.468737,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1066b6a519689bab",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "dusha-specialty-coffee",
    "name": "Dusha Specialty Coffee",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Mileševska 25, Beograd 11000",
    "lat": 44.800418,
    "lng": 20.479718,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x38464e285d0ae9cb",
    "tags": []
  },
  {
    "id": "bistro-mali-pijac",
    "name": "Bistro Mali Pijac",
    "category": "jelo",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Karađorđeva 61, Beograd 11000",
    "lat": 44.813336,
    "lng": 20.452562,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa50b06d9a86e9b62",
    "tags": []
  },
  {
    "id": "kafe-kafe-bistro",
    "name": "Kafe Kafe bistro",
    "category": "kafa",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Magistratski trg 8, Beograd",
    "lat": 44.844471,
    "lng": 20.413581,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9a44cc79fb7a7a4e",
    "tags": []
  },
  {
    "id": "zavicaj-skadarlija",
    "name": "Zavičaj Skadarlija",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "€€",
    "address": "Skadarska 18, Beograd 11000",
    "lat": 44.816734,
    "lng": 20.463733,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x33a2bfb2fd6707f0",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "nula-pet",
    "name": "Nula Pet",
    "category": "noc",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Dobračina 30a, Beograd 11158",
    "lat": 44.819205,
    "lng": 20.462556,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbd90b0a7db64a417",
    "tags": []
  },
  {
    "id": "june-cafe",
    "name": "June Cafe",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Gospodar-Jevremova 25, Beograd 11158",
    "lat": 44.820874,
    "lng": 20.459385,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa89e6e20f227f8e1",
    "tags": []
  },
  {
    "id": "pastis-bistro",
    "name": "PASTIS bistro",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Strahinjića Bana 52b, Beograd 11000",
    "lat": 44.821326,
    "lng": 20.461623,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3ca7edddd24b320",
    "tags": []
  },
  {
    "id": "aut-bistro",
    "name": "Aut Bistro",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Strahinjića Bana 64-66, Beograd 11000",
    "lat": 44.820495,
    "lng": 20.463029,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfaa8821a9058ea4b",
    "tags": []
  },
  {
    "id": "restaurant-idol",
    "name": "Restaurant IDOL",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Strahinjića Bana 61, Beograd 11000",
    "lat": 44.820714,
    "lng": 20.463301,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe58e9b571b7d77c2",
    "tags": []
  },
  {
    "id": "smokvica-kralja-petra",
    "name": "Smokvica - Kralja Petra",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "11000, Kralja Petra 73, Beograd 11000",
    "lat": 44.821698,
    "lng": 20.457322,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3afdd8298aee54a",
    "tags": []
  },
  {
    "id": "ljuki-s-barbecue",
    "name": "Ljuki's Barbecue",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "€",
    "address": "Karađorđeva 12a, Beograd 11080",
    "lat": 44.840157,
    "lng": 20.415115,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x2de8c33873c6e98b",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "beograd-na-vatri",
    "name": "Beograd na vatri",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "€€",
    "address": "Tošin bunar 148, Beograd 11070",
    "lat": 44.830377,
    "lng": 20.398892,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8745893377bf2478",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "restoran-mokum",
    "name": "Restoran Mokum",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-04",
    "price": "",
    "address": "Jug Bogdanova 10, Beograd 11000",
    "lat": 44.814176,
    "lng": 20.455662,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1474ee1645df3030",
    "tags": []
  },
  {
    "id": "iv-restaurant",
    "name": "Iv restaurant",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-03-30",
    "price": "",
    "address": "Milentija Popovića 5b, Beograd 11070",
    "lat": 44.811351,
    "lng": 20.435299,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa2c2997173af9248",
    "tags": []
  },
  {
    "id": "wiggle",
    "name": "Wiggle",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-03-04",
    "price": "",
    "address": "Pop-Lukina 1, Beograd 11000",
    "lat": 44.816955,
    "lng": 20.45302,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xebb78abbdcd7daea",
    "tags": []
  },
  {
    "id": "kafana-5-glava",
    "name": "Kafana \"5 Glava\"",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-09-20",
    "price": "",
    "address": "Cetinjska 15, Beograd",
    "lat": 44.817831,
    "lng": 20.466155,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x171ea528093ec168",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "klub-za-drustvene-igre-groot",
    "name": "Klub za drustvene igre - \"Groot\"",
    "category": "radi",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-07-03",
    "price": "",
    "address": "Narodnih heroja 7, Beograd 11070",
    "lat": 44.824438,
    "lng": 20.409053,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x23ccb9153efafb7e",
    "tags": []
  },
  {
    "id": "lenja-buba",
    "name": "Lenja Buba",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-02-04",
    "price": "",
    "address": "Žorža Klemansoa 19, Beograd 11000",
    "lat": 44.82215,
    "lng": 20.469172,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x40e8e944b95ea12a",
    "tags": []
  },
  {
    "id": "radionica",
    "name": "Radionica",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-02-04",
    "price": "",
    "address": "Dobračina 59-73, Beograd",
    "lat": 44.823233,
    "lng": 20.467591,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xacb1440a22f85d5a",
    "tags": []
  },
  {
    "id": "iva-new-balkan-cuisine",
    "name": "Iva New Balkan Cuisine",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-02-04",
    "price": "",
    "address": "Svetog Save 14, Beograd 11000",
    "lat": 44.801004,
    "lng": 20.467093,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6b150ae0b675f8cb",
    "tags": []
  },
  {
    "id": "makao-i-zuto-more-macao-and-yellow-sea",
    "name": "Makao i Žuto More (Macao and Yellow Sea)",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-09-10",
    "price": "",
    "address": "Prve pruge 8, Beograd",
    "lat": 44.835448,
    "lng": 20.416145,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9e7659047883a57",
    "tags": []
  },
  {
    "id": "restoran-radnicki",
    "name": "Restoran Radnicki",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-05-21",
    "price": "",
    "address": "Tošin bunar 190, Beograd",
    "lat": 44.824571,
    "lng": 20.395608,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x155b6fe4447dc898",
    "tags": []
  },
  {
    "id": "kolokvijum-bar",
    "name": "Kolokvijum bar",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-05-21",
    "price": "",
    "address": "Bulevar Zorana Đinđića 197, Beograd",
    "lat": 44.82376,
    "lng": 20.401676,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6dff0c2ff7e7b564",
    "tags": []
  },
  {
    "id": "coffeedream",
    "name": "Coffeedream",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-04-09",
    "price": "",
    "address": "Bulevar Arsenija Čarnojevića 186, Beograd 11070",
    "lat": 44.822999,
    "lng": 20.401975,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1e80e111b3ef5287",
    "tags": []
  },
  {
    "id": "barrel-house",
    "name": "Barrel House",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-04-09",
    "price": "",
    "address": "Žorža Klemansoa 19, Beograd 11000",
    "lat": 44.82208,
    "lng": 20.469105,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3688917e4e981e5d",
    "tags": []
  },
  {
    "id": "rodizio",
    "name": "Rodizio",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-04-09",
    "price": "€€€",
    "address": "Bulevar Milutina Milankovića 11b, Beograd",
    "lat": 44.813507,
    "lng": 20.407423,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbd002651dd494e4e",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "mmr-escape-rooms-lokacija-2",
    "name": "MMR Escape Rooms: Lokacija 2",
    "category": "radi",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-03-22",
    "price": "",
    "address": "Milutina Milankovića 98, Beograd 11000",
    "lat": 44.811318,
    "lng": 20.415101,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6c69879dbcf6ce21",
    "tags": []
  },
  {
    "id": "smash-burgers",
    "name": "SMASH BURGERS",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2022-12-04",
    "price": "",
    "address": "Takovska 50, Beograd",
    "lat": 44.81489,
    "lng": 20.475084,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x42011dc251b8c555",
    "tags": []
  },
  {
    "id": "schmizza-krilca",
    "name": "Schmizza Krilca",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-10-03",
    "price": "",
    "address": "Bulevar Marsala Tolbuhina 2c, Maršala Tolbuhina 2 c, 11080",
    "lat": 44.831427,
    "lng": 20.418009,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x598d6288ed60dd1a",
    "tags": []
  },
  {
    "id": "mirovica",
    "name": "Mirovica",
    "category": "jelo",
    "area": "Boleč",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-08-04",
    "price": "€€€",
    "address": "Smederevski put 1, Boleč 11306",
    "lat": 44.743943,
    "lng": 20.606174,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe4169437acc56fea",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "chick-n-bun-x-bao-fusion",
    "name": "Chick n' Bun x Bao Fusion",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-05-21",
    "price": "€",
    "address": "Dubrovačka 17, Beograd 11000",
    "lat": 44.82562,
    "lng": 20.46146,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x61c4ebe9dd618b8e",
    "tags": []
  },
  {
    "id": "kaiserschmarrn",
    "name": "Kaiserschmarrn",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-04-23",
    "price": "",
    "address": "Vuka Karadžića 9, Beograd 11000",
    "lat": 44.817294,
    "lng": 20.455339,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd185a33c042a3794",
    "tags": []
  },
  {
    "id": "del-mar",
    "name": "Del Mar",
    "category": "jelo",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-04-05",
    "price": "",
    "address": "Belgrade",
    "lat": 44.786667,
    "lng": 20.395369,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfe30ea1d2678f38",
    "tags": []
  },
  {
    "id": "pingvin",
    "name": "Pingvin",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-03-25",
    "price": "",
    "address": "obala, Savski kej, Beograd 11070",
    "lat": 44.795568,
    "lng": 20.395845,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xdeb655a95cb24110",
    "tags": []
  },
  {
    "id": "historical-museum-of-serbia",
    "name": "Historical Museum of Serbia",
    "category": "vidi",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-03-19",
    "price": "",
    "address": "Trg Nikole Pašića 11, Beograd 11000",
    "lat": 44.812501,
    "lng": 20.463771,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1e15d803ea02e273",
    "tags": []
  },
  {
    "id": "sentimenti",
    "name": "Sentimenti",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2026-01-22",
    "price": "",
    "address": "Cara Lazara 5-7, Beograd 11000",
    "lat": 44.818553,
    "lng": 20.454273,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x32360b4b756d1377",
    "tags": []
  },
  {
    "id": "meze-by-elliniko-belgrade",
    "name": "Meze by Elliniko Belgrade",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-12-29",
    "price": "€€€",
    "address": "Bulevar maršala Tolbuhina 34A, Beograd 11070",
    "lat": 44.830483,
    "lng": 20.408834,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3bd6cf9e32e39413",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "kokpit-cafeteria",
    "name": "KOKPIT cafeteria",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-12-23",
    "price": "€€",
    "address": "Đorđa Stanojevića 9G, Beograd 11070",
    "lat": 44.805832,
    "lng": 20.406717,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x901a7348ad029311",
    "tags": []
  },
  {
    "id": "restoran-bigz-011",
    "name": "Restoran Bigz 011",
    "category": "pice",
    "area": "Savski venac",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-12-14",
    "price": "",
    "address": "Bulevar vojvode Mišića 17, Beograd 11000",
    "lat": 44.797313,
    "lng": 20.446745,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf3170aa7dd7ceec1",
    "tags": []
  },
  {
    "id": "bottega-galerija",
    "name": "Bottega Galerija",
    "category": "jelo",
    "area": "Beograd na vodi",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-11-22",
    "price": "",
    "address": "Bulevar Vudro Vilson 12, Beograd 11000",
    "lat": 44.80242,
    "lng": 20.44421,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc06230cd70016d79",
    "tags": []
  },
  {
    "id": "morava-meat-concept-store",
    "name": "Morava - Meat Concept Store",
    "category": "jelo",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-11-15",
    "price": "€€",
    "address": "Ilije Garašanina 5c, Beograd",
    "lat": 44.81151,
    "lng": 20.472185,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc2d37b3e2bf23d5e",
    "tags": []
  },
  {
    "id": "supertramp-bar-belgrade",
    "name": "Supertramp Bar Belgrade",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-10-23",
    "price": "€€",
    "address": "Maršala Birjuzova 10A, Beograd 11000",
    "lat": 44.814851,
    "lng": 20.458458,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x614e2fde0b5a7ba0",
    "tags": []
  },
  {
    "id": "kafeterija-kofilin",
    "name": "Kafeterija Kofilin",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-09-20",
    "price": "",
    "address": "Kneginje Zorke 40, Beograd 11000",
    "lat": 44.801408,
    "lng": 20.470553,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb9dff91f9d04a919",
    "tags": []
  },
  {
    "id": "stamevski",
    "name": "Stamevski",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-09-11",
    "price": "",
    "address": "Belgrade",
    "lat": 44.819796,
    "lng": 20.412203,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x60c2f0815c44632b",
    "tags": []
  },
  {
    "id": "shootiranje",
    "name": "Shootiranje",
    "category": "noc",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-09-07",
    "price": "",
    "address": "Gavrila Principa 7, Beograd 11101",
    "lat": 44.813609,
    "lng": 20.454506,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x619c58cd72cb6164",
    "tags": []
  },
  {
    "id": "konoha",
    "name": "Konoha",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-09-03",
    "price": "€€€",
    "address": "Njegoševa 51, Beograd 11080",
    "lat": 44.847888,
    "lng": 20.412631,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3738815f674a36fe",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "lucky-plate",
    "name": "Lucky Plate",
    "category": "pice",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-08-12",
    "price": "",
    "address": "Bulevar despota Stefana 19, Beograd 11000",
    "lat": 44.816784,
    "lng": 20.466205,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe3f7ab95f6033c44",
    "tags": []
  },
  {
    "id": "mama-goca",
    "name": "Mama Goca",
    "category": "kafa",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-08-09",
    "price": "",
    "address": "Džona Kenedija 31g, Beograd 11080",
    "lat": 44.833077,
    "lng": 20.411878,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xdb94cd48786c1632",
    "tags": []
  },
  {
    "id": "restoran-potpis",
    "name": "Restoran Potpis",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-07-10",
    "price": "€€€",
    "address": "Orlovića Pavla 15, Beograd 122503",
    "lat": 44.796997,
    "lng": 20.476034,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x660653b25c7809c7",
    "tags": []
  },
  {
    "id": "moba-plantbased",
    "name": "Moba Plantbased",
    "category": "jelo",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-06-09",
    "price": "€",
    "address": "Ćirila i Metodija 2, Beograd 11050",
    "lat": 44.804045,
    "lng": 20.481537,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc63d6a9958f3c1a7",
    "tags": []
  },
  {
    "id": "jevremovac-botanical-garden",
    "name": "Jevremovac Botanical Garden",
    "category": "vidi",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-06-09",
    "price": "",
    "address": "Takovska 43, Beograd",
    "lat": 44.814344,
    "lng": 20.473289,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xcc03952014b63d3e",
    "tags": []
  },
  {
    "id": "kuca-umetnica",
    "name": "Kuća Umetnica",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-06-09",
    "price": "",
    "address": "Gospodar-Jevremova 25, Beograd 11000",
    "lat": 44.820827,
    "lng": 20.459472,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x4d8fa86ac5e8c101",
    "tags": []
  },
  {
    "id": "peers-cafe",
    "name": "Peers.cafe",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-06-03",
    "price": "€€€",
    "address": "Dunavski kej 48, Beograd 11000",
    "lat": 44.827928,
    "lng": 20.471952,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x72f2a97b99c12398",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "flat-burger-bg",
    "name": "Flat Burger BG",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-06-02",
    "price": "",
    "address": "Dečanska 4, Beograd 11000",
    "lat": 44.815439,
    "lng": 20.462173,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xced09789b1547abf",
    "tags": []
  },
  {
    "id": "lorenzo-kakalamba",
    "name": "Lorenzo & Kakalamba",
    "category": "jelo",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-05-30",
    "price": "",
    "address": "Cvijićeva 110, Beograd 11000",
    "lat": 44.809582,
    "lng": 20.480389,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8a284aea0b3d1685",
    "tags": []
  },
  {
    "id": "time-story",
    "name": "Time Story",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-05-28",
    "price": "",
    "address": "Ugrinovačka 124, Beograd",
    "lat": 44.849944,
    "lng": 20.388194,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5cc9ca924d96e3b5",
    "tags": []
  },
  {
    "id": "draft-bar",
    "name": "Draft Bar",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-05-28",
    "price": "",
    "address": "Žorža Klemansoa 29d, Beograd 11000",
    "lat": 44.824308,
    "lng": 20.471736,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x63fefc9f69818643",
    "tags": []
  },
  {
    "id": "harats-pub-belgrade",
    "name": "Harat’s Pub Belgrade",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-28",
    "price": "",
    "address": "Kralja Petra 18, Beograd 11000",
    "lat": 44.819014,
    "lng": 20.454326,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x588274ee3bffa5b9",
    "tags": []
  },
  {
    "id": "buena-vida-beograd",
    "name": "Buena Vida Beograd",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-13",
    "price": "",
    "address": "Bulevar Milutina Milankovića 1i, Beograd 11070",
    "lat": 44.806201,
    "lng": 20.422619,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x20e5297779a74471",
    "tags": []
  },
  {
    "id": "intergalactic-diner-novi-beograd",
    "name": "Intergalactic Diner Novi Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-13",
    "price": "€€",
    "address": "Omladinskih brigada 16a, Beograd 11070",
    "lat": 44.822072,
    "lng": 20.410768,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x213f62cd20fc9171",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "nacionalna-klasa-beograd",
    "name": "Nacionalna Klasa Beograd",
    "category": "noc",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-12",
    "price": "",
    "address": "Ušće 11, Beograd 11000",
    "lat": 44.819144,
    "lng": 20.443928,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8195bf642da3e617",
    "tags": []
  },
  {
    "id": "kafeterija-skyline",
    "name": "Kafeterija | Skyline",
    "category": "kafa",
    "area": "Savski venac",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-09",
    "price": "",
    "address": "Kneza Miloša 90A, Beograd 11000",
    "lat": 44.799981,
    "lng": 20.451712,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbfa165ee2c511026",
    "tags": []
  },
  {
    "id": "riddle-bar",
    "name": "Riddle Bar",
    "category": "pice",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-09",
    "price": "",
    "address": "Skadarska 9, Beograd 11000",
    "lat": 44.816937,
    "lng": 20.463572,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x430e38ec210c5fbf",
    "tags": []
  },
  {
    "id": "sweet-n-cili",
    "name": "Sweet 'n' Čili",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-09",
    "price": "",
    "address": "Strahinjića Bana 72a, Beograd 11000",
    "lat": 44.81963,
    "lng": 20.464487,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5924eed59735420f",
    "tags": []
  },
  {
    "id": "kafeterija-sank",
    "name": "Kafeterija Šank",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-09",
    "price": "",
    "address": "Nedeljka Gvozdenovića 21, Beograd 11070",
    "lat": 44.812476,
    "lng": 20.37183,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xff0a2a11e05117b1",
    "tags": []
  },
  {
    "id": "central-pub",
    "name": "Central Pub",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-09",
    "price": "",
    "address": "Bulevar Zorana Đinđića 106a, Beograd 11070",
    "lat": 44.822064,
    "lng": 20.409232,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x709d011e46b14bd2",
    "tags": []
  },
  {
    "id": "prekoputa-proleca",
    "name": "Prekoputa Proleća",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2025-04-04",
    "price": "",
    "address": "Vuka Karadžića 14, Beograd 11000",
    "lat": 44.817328,
    "lng": 20.455136,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xce695aaf05cc04a3",
    "tags": []
  },
  {
    "id": "kafeterija-gundulicev-venac",
    "name": "Kafeterija Gundulićev venac",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2024-02-04",
    "price": "",
    "address": "Gundulićev venac 59a, Beograd",
    "lat": 44.82181,
    "lng": 20.466967,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x60ba5c1783ed35c",
    "tags": []
  },
  {
    "id": "smash-burgers-novi-beograd",
    "name": "SMASH BURGERS Novi Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 4,
    "date": "2023-03-22",
    "price": "€",
    "address": "Omladinskih brigada 18b, Beograd 11070",
    "lat": 44.821713,
    "lng": 20.410032,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x2c883d0c4cc14583",
    "tags": []
  },
  {
    "id": "narodno-pozoriste",
    "name": "Narodno pozorište",
    "category": "radi",
    "area": "Stari grad",
    "image": "",
    "short": "Opera, balet i drama u najlepšoj pozorišnoj zgradi u gradu, na Trgu republike.",
    "description": "Najstarije i najveće pozorište u Srbiji. Program se smenjuje između opere, baleta i drame. Za balet ili operu nije potrebno znanje srpskog, pa je ovo odličan izbor i za goste iz inostranstva.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Francuska 3, Beograd",
    "lat": 44.8166,
    "lng": 20.4602,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "opera",
      "balet"
    ],
    "icon": "🎭"
  },
  {
    "id": "jugoslovensko-dramsko-pozoriste",
    "name": "Jugoslovensko dramsko pozorište",
    "category": "radi",
    "area": "Centar",
    "image": "",
    "short": "Najjača drama u gradu, predstave se često rasprodaju danima unapred.",
    "description": "Pozorište sa najpoznatijim glumcima i predstavama koje se igraju godinama. Karte kupi ranije, posebno za vikend.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Kralja Milana 50, Beograd",
    "lat": 44.8063,
    "lng": 20.4664,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "drama"
    ],
    "icon": "🎭"
  },
  {
    "id": "atelje-212",
    "name": "Atelje 212",
    "category": "radi",
    "area": "Centar",
    "image": "",
    "short": "Savremena drama u kultnom pozorištu u Svetogorskoj ulici.",
    "description": "Pozorište koje je od šezdesetih poznato po hrabrom i savremenom repertoaru. Posle predstave Svetogorska je puna barova za piće.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Svetogorska 21, Beograd",
    "lat": 44.8125,
    "lng": 20.4718,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "drama"
    ],
    "icon": "🎭"
  },
  {
    "id": "bitef-teatar",
    "name": "Bitef teatar",
    "category": "radi",
    "area": "Dorćol",
    "image": "",
    "short": "Pozorište u nekadašnjoj crkvi, poznato po plesu i eksperimentalnim predstavama.",
    "description": "Neobičan prostor i program koji se razlikuje od klasičnih pozorišta: savremeni ples, fizičko pozorište i gostovanja.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Skver Mire Trailović 1, Beograd",
    "lat": 44.8175,
    "lng": 20.473,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "ples"
    ],
    "icon": "🎭"
  },
  {
    "id": "pozoriste-na-terazijama",
    "name": "Pozorište na Terazijama",
    "category": "radi",
    "area": "Centar",
    "image": "",
    "short": "Mjuzikli u srcu grada, zabava i kad ne razumeš jezik.",
    "description": "Glavna beogradska scena za mjuzikle. Muzika i ples nose predstavu, pa je dobar izbor za veče u gradu.",
    "rating": null,
    "source": "predlog",
    "price": "€€",
    "address": "Terazije 29, Beograd",
    "lat": 44.8128,
    "lng": 20.4613,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "mjuzikl"
    ],
    "icon": "🎭"
  },
  {
    "id": "madlenianum",
    "name": "Madlenianum",
    "category": "radi",
    "area": "Zemun",
    "image": "",
    "short": "Opera i mjuzikl u Zemunu, na Glavnoj ulici.",
    "description": "Moderno pozorište u Zemunu sa operom, mjuziklima i dramom. Spoji predstavu sa šetnjom zemunskim kejom.",
    "rating": null,
    "source": "predlog",
    "price": "€€",
    "address": "Glavna 32, Zemun",
    "lat": 44.8433,
    "lng": 20.4094,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "opera"
    ],
    "icon": "🎭"
  },
  {
    "id": "kolarceva-zaduzbina",
    "name": "Kolarčeva zadužbina",
    "category": "radi",
    "area": "Stari grad",
    "image": "",
    "short": "Klasični koncerti u koncertnoj dvorani sa sjajnom akustikom.",
    "description": "Jedna od glavnih koncertnih dvorana u gradu, čest dom Beogradske filharmonije. Proveri program za vikend koncerte.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Studentski trg 5, Beograd",
    "lat": 44.8187,
    "lng": 20.458,
    "mapsUrl": "",
    "tags": [
      "koncert",
      "klasična muzika"
    ],
    "icon": "🎻"
  },
  {
    "id": "kombank-dvorana",
    "name": "Kombank dvorana",
    "category": "radi",
    "area": "Centar",
    "image": "",
    "short": "Koncerti i stand-up u nekadašnjoj Dvorani Doma sindikata.",
    "description": "Velika sala u samom centru grada sa koncertima, stand-up komedijom i festivalima. Pogledaj program pre dolaska.",
    "rating": null,
    "source": "predlog",
    "price": "€€",
    "address": "Dečanska 14, Beograd",
    "lat": 44.8134,
    "lng": 20.4652,
    "mapsUrl": "",
    "tags": [
      "koncert",
      "stand-up"
    ],
    "icon": "🎤"
  },
  {
    "id": "jugoslovenska-kinoteka",
    "name": "Jugoslovenska kinoteka",
    "category": "radi",
    "area": "Stari grad",
    "image": "",
    "short": "Klasici svetskog filma na velikom platnu i mali muzej filma.",
    "description": "Za ljubitelje filma: retrospektive, klasici i restaurirane kopije po povoljnim cenama, u zgradi sa muzejem kinematografije.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Uzun Mirkova 1, Beograd",
    "lat": 44.818,
    "lng": 20.4555,
    "mapsUrl": "",
    "tags": [
      "film",
      "bioskop"
    ],
    "icon": "🎬"
  },
  {
    "id": "dom-omladine",
    "name": "Dom omladine Beograda",
    "category": "radi",
    "area": "Centar",
    "image": "",
    "short": "Koncerti, festivali i tribine, uvek nešto zanimljivo u programu.",
    "description": "Kulturni centar sa koncertima manjih bendova, filmskim projekcijama i festivalima. Dobar izbor kad hoćeš nešto drugačije od kafane.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Makedonska 22, Beograd",
    "lat": 44.8148,
    "lng": 20.4637,
    "mapsUrl": "",
    "tags": [
      "koncert",
      "kultura"
    ],
    "icon": "🎸"
  },
  {
    "id": "krstarenje-rekom",
    "name": "Krstarenje Savom i Dunavom",
    "category": "radi",
    "area": "Savamala",
    "image": "",
    "short": "Sat vremena na reci uz najlepši pogled na tvrđavu i ušće.",
    "description": "Brodići kreću sa pristaništa u Savamali i plove oko Velikog ratnog ostrva i ispod tvrđave. Najlepše je pred zalazak sunca.",
    "rating": null,
    "source": "predlog",
    "price": "€€",
    "address": "Pristanište, Karađorđeva, Beograd",
    "lat": 44.8172,
    "lng": 20.4489,
    "mapsUrl": "",
    "tags": [
      "reka",
      "zalazak"
    ],
    "icon": "⛴️"
  },
  {
    "id": "bicikl-ada-ciganlija",
    "name": "Bicikl oko Ade Ciganlije",
    "category": "radi",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "Krug oko jezera biciklom, bicikl se iznajmljuje na samoj Adi.",
    "description": "Ravna staza oko celog jezera, sa kafićima i plažama usput. Leti spoji sa kupanjem.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Ada Ciganlija, Beograd",
    "lat": 44.787,
    "lng": 20.414,
    "mapsUrl": "",
    "tags": [
      "sport",
      "leto"
    ],
    "icon": "🚲"
  },
  {
    "id": "zooloski-vrt",
    "name": "Beogradski zoološki vrt",
    "category": "radi",
    "area": "Stari grad",
    "image": "",
    "short": "Zoo vrt u okviru Beogradske tvrđave, dobar za porodice.",
    "description": "Mali zoo vrt na Kalemegdanu. Posle obilaska nastavi šetnju zidinama tvrđave.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Mali Kalemegdan 8, Beograd",
    "lat": 44.8247,
    "lng": 20.4521,
    "mapsUrl": "",
    "tags": [
      "porodica"
    ],
    "icon": "🦁"
  },
  {
    "id": "kalemegdan",
    "name": "Kalemegdan i Beogradska tvrđava",
    "category": "vidi",
    "area": "Stari grad",
    "image": "",
    "short": "Šetnja zidinama i zalazak sunca nad ušćem Save u Dunav.",
    "description": "Srce grada: park, zidine, Pobednik i vidikovac iznad ušća. Dođi sat vremena pre zalaska sunca.",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Kalemegdan, Beograd",
    "lat": 44.8231,
    "lng": 20.4506,
    "mapsUrl": "",
    "tags": [
      "pogled",
      "zalazak",
      "besplatno"
    ],
    "icon": "🏰"
  },
  {
    "id": "hram-svetog-save",
    "name": "Hram Svetog Save",
    "category": "vidi",
    "area": "Vračar",
    "image": "",
    "short": "Monumentalni hram, obavezno siđi u kriptu sa zlatnim mozaicima.",
    "description": "Jedan od najvećih pravoslavnih hramova na svetu. Kripta je najmirnija ujutru, a plato ispred je odličan za odmor.",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Krušedolska 2a, Beograd",
    "lat": 44.7981,
    "lng": 20.4689,
    "mapsUrl": "",
    "tags": [
      "arhitektura",
      "besplatno"
    ],
    "icon": "⛪"
  },
  {
    "id": "muzej-nikole-tesle",
    "name": "Muzej Nikole Tesle",
    "category": "vidi",
    "area": "Vračar",
    "image": "",
    "short": "Vođene ture i demonstracija Teslinog kalema.",
    "description": "Mali muzej sa vođenim turama i živim demonstracijama. Dođi ranije jer se ture brzo popune.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Krunska 51, Beograd",
    "lat": 44.8059,
    "lng": 20.4719,
    "mapsUrl": "",
    "tags": [
      "muzej",
      "kišni dan"
    ],
    "icon": "⚡"
  },
  {
    "id": "muzej-jugoslavije",
    "name": "Muzej Jugoslavije",
    "category": "vidi",
    "area": "Savski venac",
    "image": "",
    "short": "Kuća cveća i istorija Jugoslavije na jednom mestu.",
    "description": "Kompleks sa Kućom cveća i stalnim izložbama o Jugoslaviji. Lepo uređen park i dobar pogled sa brda.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Botićeva 6, Beograd",
    "lat": 44.7868,
    "lng": 20.4512,
    "mapsUrl": "",
    "tags": [
      "muzej",
      "istorija"
    ],
    "icon": "🖼️"
  },
  {
    "id": "gardos-kula",
    "name": "Gardoš kula",
    "category": "vidi",
    "area": "Zemun",
    "image": "",
    "short": "Kula iznad Zemuna sa pogledom na Dunav i crvene krovove.",
    "description": "Popni se uzanim zemunskim uličicama do kule. Spoji sa ručkom na zemunskom keju.",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Grobljanska, Zemun",
    "lat": 44.8481,
    "lng": 20.4097,
    "mapsUrl": "",
    "tags": [
      "pogled",
      "besplatno"
    ],
    "icon": "🏰"
  },
  {
    "id": "avalski-toranj",
    "name": "Avalski toranj",
    "category": "vidi",
    "area": "Avala",
    "image": "",
    "short": "Vidikovac na vrhu tornja sa pogledom na ceo Beograd.",
    "description": "Izlet na planinu Avala, pola sata od centra. Šuma za šetnju i vidikovac na vrhu tornja.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Avala, Beograd",
    "lat": 44.6955,
    "lng": 20.515,
    "mapsUrl": "",
    "tags": [
      "izlet",
      "pogled"
    ],
    "icon": "🗼"
  }
];
