/*
  STEFANOV VODIČ – podaci o lokacijama
  ------------------------------------
  Ovde su samo mesta koja se pojavljuju na top listama (js/lists.js).
  Mesto koje dodaješ na listu prvo upiši ovde, pa njegov id stavi u listu.
  Slobodno menjaj, dodaj ili obriši bilo koje mesto. Svako mesto je jedan objekat.

  Polja:
    id          jedinstveni kratki naziv, bez razmaka (npr. "kalemegdan")
    name        naziv mesta
    category    jedna od: "jelo", "kafa", "pice", "vidi", "radi", "noc"
    area        kraj grada (npr. "Dorćol", "Zemun", "Vračar")
    image       (opciono) putanja do tvoje slike u folderu images/ (npr. "images/kalemegdan.jpg")
                ako je prazno, sajt uzima fotografiju sa Google Maps (potreban ključ)
    short       (opciono) jedna rečenica o mestu (short_en: na engleskom)
    description (opciono) duži opis u detaljima (description_en: na engleskom)
    tip         (opciono) poseban Stefanov savet
    rating      Stefanova ocena (1 do 5), prikazuje se kao "Stefanova ocena" dok nema Google ocene
    googleRating  (opciono) prosečna ocena mesta na Google Maps, npr. 4.7
    googleReviews (opciono) broj recenzija na Google Maps, npr. 145
                  Prepiši ih sa Google Maps za mesta koja želiš. Sa Google ključem stižu same.
    date        datum recenzije
    price       "€", "€€", "€€€" ili "" ako nije poznato
    address     adresa
    lat, lng    koordinate
    mapsUrl     link ka mestu na Google Maps
    tags        lista kratkih oznaka
    icon        (opciono) ilustracija za pin i poster (npr. "🎭")
    source      "predlog" za mesta koja nisu iz tvojih recenzija
    placeId     (opciono) Google Place ID, ako Google nađe pogrešnu fotografiju
*/

const CATEGORIES = {
  jelo: { label: "Jelo", icon: "🍽️" },
  kafa: { label: "Kafa i slatko", icon: "☕" },
  pice: { label: "Piće", icon: "🍸" },
  vidi: { label: "Vidi", icon: "🏛️" },
  radi: { label: "Aktivnosti", icon: "🎟️" },
  noc: { label: "Noćni život", icon: "🌙" },
};

const LOCATIONS = [
  {
    "id": "peak-place",
    "name": "Peak Place",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-09-09",
    "price": "",
    "address": "Bulevar Zorana Đinđića, Beograd",
    "lat": 44.812617,
    "lng": 20.429756,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x16d2ecb35895d6e3",
    "tags": []
  },
  {
    "id": "cetiri-coffee-bar",
    "name": "Cetiri coffee bar",
    "category": "kafa",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-08-23",
    "price": "",
    "address": "Terazije 36, Beograd 11000",
    "lat": 44.811433,
    "lng": 20.461696,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xab606969b6f61ab",
    "tags": []
  },
  {
    "id": "gradska-przionica",
    "name": "Gradska Pržionica",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-06-13",
    "price": "",
    "address": "Dunavski kej 46, Beograd",
    "lat": 44.827493,
    "lng": 20.471522,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xef5dbc86abbdfb78",
    "tags": [],
    "googleRating": 4.7,
    "googleReviews": 145
  },
  {
    "id": "turbomax-karting-centar",
    "name": "Turbomax Karting centar",
    "category": "radi",
    "area": "Višnjica",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-05-20",
    "price": "",
    "address": "Pančevački Put 81, Beograd 11210",
    "lat": 44.852447,
    "lng": 20.52921,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x64e8d33549345571",
    "tags": []
  },
  {
    "id": "ustipak-bar-vracar",
    "name": "Uštipak bar Vračar",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-28",
    "price": "€",
    "address": "Njegoševa BB, Kalenić pijaca lokal 28, Beograd",
    "lat": 44.799798,
    "lng": 20.475379,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd17047fb5b7de04d",
    "tags": [
      "doručak"
    ]
  },
  {
    "id": "meduza",
    "name": "Meduza",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-26",
    "price": "",
    "address": "Gospodar-Jevremova 6, Beograd 11000",
    "lat": 44.822326,
    "lng": 20.456348,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1247acabfa35dc64",
    "tags": []
  },
  {
    "id": "muzej-paranormalnog",
    "name": "Muzej paranormalnog",
    "category": "vidi",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-24",
    "price": "",
    "address": "Zmaj Jovina 4, Beograd 11000",
    "lat": 44.816657,
    "lng": 20.457068,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb0246e61d60c2fef",
    "tags": []
  },
  {
    "id": "pivokratija-2",
    "name": "Pivokratija 2",
    "category": "pice",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-04-20",
    "price": "",
    "address": "Savski nasip bb, Beograd 11070",
    "lat": 44.800813,
    "lng": 20.417473,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x76bc2ea769c13bf4",
    "tags": []
  },
  {
    "id": "buratina-bar",
    "name": "BURATINA Bar",
    "category": "pice",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-07",
    "price": "",
    "address": "Svetogorska 46, Beograd 11103",
    "lat": 44.812783,
    "lng": 20.469915,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x64e5baa7cfacbf04",
    "tags": []
  },
  {
    "id": "cin-cin",
    "name": "Čin Čin",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-06",
    "price": "€",
    "address": "Radoslava Grujića 28, Beograd 11000",
    "lat": 44.800793,
    "lng": 20.480795,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb4ae30d45282838a",
    "tags": []
  },
  {
    "id": "eje-belgrade",
    "name": "EJE Belgrade",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-03-06",
    "price": "",
    "address": "Dobračina 39, Beograd 11000",
    "lat": 44.820638,
    "lng": 20.463911,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x39b927b7bc3bad42",
    "tags": []
  },
  {
    "id": "dogma-brewery-tap-room",
    "name": "Dogma Brewery & Tap Room",
    "category": "pice",
    "area": "Ada Ciganlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-01-31",
    "price": "",
    "address": "Radnička 3 Čukarica Belgrade, 11030",
    "lat": 44.788478,
    "lng": 20.423116,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa14f065b87591bc6",
    "tags": []
  },
  {
    "id": "perlo-burgeri",
    "name": "Perlo burgeri",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2026-01-17",
    "price": "",
    "address": "Đure Jakšića br. 3, Beograd 11000",
    "lat": 44.817439,
    "lng": 20.456614,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x632850d20984f50c",
    "tags": []
  },
  {
    "id": "avocado-belvil",
    "name": "Avocado Belvil",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-30",
    "price": "",
    "address": "Đorđa Stanojevića 9b, Beograd 11070",
    "lat": 44.806678,
    "lng": 20.406826,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x26e76dbc61b2240d",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "badger-mug",
    "name": "Badger & Mug",
    "category": "pice",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-20",
    "price": "",
    "address": "Nušićeva 6, Beograd 11102",
    "lat": 44.813799,
    "lng": 20.461656,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf1106025125cec59",
    "tags": []
  },
  {
    "id": "liga-pub-obilicev-venac",
    "name": "Liga Pub Obilicev venac",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-20",
    "price": "",
    "address": "Obilićev venac 29, Beograd 11000",
    "lat": 44.815627,
    "lng": 20.459072,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x43d0bbeb78672d10",
    "tags": []
  },
  {
    "id": "espresso-bar",
    "name": "Espresso bar",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-20",
    "price": "",
    "address": "Topličin venac 7, Beograd 11000",
    "lat": 44.816168,
    "lng": 20.45589,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7d9ec2d26e02ecc4",
    "tags": []
  },
  {
    "id": "ugao-specialty-coffee",
    "name": "UGAO Specialty Coffee",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-06",
    "price": "€",
    "address": "Dunavska 2i, Beograd 11000",
    "lat": 44.828572,
    "lng": 20.45257,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa6490bbdd93ee18d",
    "tags": []
  },
  {
    "id": "sloj-bistro-bakery-waterfront",
    "name": "SLOJ bistro & bakery WATERFRONT",
    "category": "kafa",
    "area": "Beograd na vodi",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-06",
    "price": "",
    "address": "Bulevar Vudroa Vilsona 8V, Beograd 11000",
    "lat": 44.80564,
    "lng": 20.450985,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x31888f49f5a6bf26",
    "tags": []
  },
  {
    "id": "cafe-934",
    "name": "Cafe 9¾",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-12-03",
    "price": "",
    "address": "Dunavska 2a, Beograd 11000",
    "lat": 44.828322,
    "lng": 20.454708,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x66a26851fb4acd63",
    "tags": []
  },
  {
    "id": "lefer-splav",
    "name": "LeFer Splav",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-22",
    "price": "",
    "address": "Gandijeva BB, Beograd 11070",
    "lat": 44.795358,
    "lng": 20.392997,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe259a7cc9ede5ba1",
    "tags": []
  },
  {
    "id": "tokar-kafeterija",
    "name": "Tokar Kafeterija",
    "category": "kafa",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-15",
    "price": "",
    "address": "Kneza Danila 9, Beograd 11000",
    "lat": 44.810777,
    "lng": 20.476648,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3bfde72cf773163f",
    "tags": []
  },
  {
    "id": "bistro-tri",
    "name": "Bistro Tri",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-11-09",
    "price": "€",
    "address": "Mileševska 16, Beograd 11000",
    "lat": 44.800653,
    "lng": 20.477805,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xcfd2454f26e451ec",
    "tags": []
  },
  {
    "id": "monk-s-bar",
    "name": "Monk's Bar",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-26",
    "price": "",
    "address": "71 KNJEGINJE ZORKE, 11104, Belgrade (Vracar), Belgrade county",
    "lat": 44.803306,
    "lng": 20.472181,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xeb8098b405f280ff",
    "tags": []
  },
  {
    "id": "velika-skadarlija-restaurant",
    "name": "Velika Skadarlija restaurant",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-10",
    "price": "€€€",
    "address": "Skadarska 40d, Beograd",
    "lat": 44.818687,
    "lng": 20.466337,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xff2b548f5e8f2adf",
    "tags": []
  },
  {
    "id": "giovanni-s-pizzeria",
    "name": "Giovanni's Pizzeria",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-10-07",
    "price": "€€€",
    "address": "Gračanička 11, Beograd 11000",
    "lat": 44.817795,
    "lng": 20.454405,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x94263cf6190f1141",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "im-camy-lunch-bar",
    "name": "i’m Camy Lunch Bar",
    "category": "kafa",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-28",
    "price": "€",
    "address": "Pavla Vuisića 69 B, Beograd 11080",
    "lat": 44.853065,
    "lng": 20.347089,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8a87febe437edaf0",
    "tags": [
      "doručak"
    ]
  },
  {
    "id": "passengers-bar",
    "name": "Passengers Bar",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-24",
    "price": "",
    "address": "Simina 5, Beograd 11000",
    "lat": 44.820333,
    "lng": 20.459081,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x68b262c958d11bb4",
    "tags": []
  },
  {
    "id": "sava-45-event-center",
    "name": "Sava 45 event center",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-21",
    "price": "",
    "address": "Savski kej 83, Beograd 11070",
    "lat": 44.793736,
    "lng": 20.382812,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb8cad03faec8929a",
    "tags": []
  },
  {
    "id": "poslasticarnica-kostana",
    "name": "Poslastičarnica Koštana",
    "category": "kafa",
    "area": "Palilula",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-19",
    "price": "",
    "address": "Bulevar kralja Aleksandra 93, Beograd 11000",
    "lat": 44.802456,
    "lng": 20.483041,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6332da8dd86055c2",
    "tags": []
  },
  {
    "id": "leposava-bar",
    "name": "Leposava bar",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-13",
    "price": "€",
    "address": "Velike stepenice 6, Beograd 11000",
    "lat": 44.818462,
    "lng": 20.450372,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc9b0fe53e9684",
    "tags": []
  },
  {
    "id": "ciribu-ciriba",
    "name": "Ćiribu Ćiriba",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-11",
    "price": "€€",
    "address": "Masarikov trg 6, Beograd 11080",
    "lat": 44.844229,
    "lng": 20.415132,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbf2a0a9aee87ab0",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "between-espresso-wine-bar",
    "name": "Between Espresso & Wine Bar",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-10",
    "price": "€",
    "address": "Strahinjića Bana 59, Beograd 11158",
    "lat": 44.820827,
    "lng": 20.463153,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfa6d8bb183fe4c5",
    "tags": []
  },
  {
    "id": "brekky",
    "name": "Brekky",
    "category": "kafa",
    "area": "Beograd na vodi",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-05",
    "price": "",
    "address": "Bulevar Vudroa Vilsona 10, Beograd 11000",
    "lat": 44.805174,
    "lng": 20.45062,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf0cfab259cf8115c",
    "tags": []
  },
  {
    "id": "beishanlan-bubble-tea",
    "name": "Beishanlan Bubble Tea",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-09-02",
    "price": "",
    "address": "Serbia, Beograd, Maršala Birjuzova, RS 贝尔格莱德 Maršala Birjuzova 1, Beograd 11000邮政编码: 11000",
    "lat": 44.814275,
    "lng": 20.45887,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x274418b5e34fff6a",
    "tags": []
  },
  {
    "id": "taurunum-pogled-pizza-bar",
    "name": "Taurunum Pogled Pizza Bar",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-22",
    "price": "€€",
    "address": "Sinđelićeva 30, Beograd",
    "lat": 44.848729,
    "lng": 20.411024,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe7cf7cef088cf301",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "bure-piva",
    "name": "Bure Piva",
    "category": "pice",
    "area": "Konjarnik",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-09",
    "price": "",
    "address": "Živka Davidovića 89, Beograd 11000",
    "lat": 44.786789,
    "lng": 20.514824,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x4f261ec772e7121",
    "tags": []
  },
  {
    "id": "adam-stroopwafel",
    "name": "A’dam Stroopwafel",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-08-05",
    "price": "",
    "address": "Nikole Spasića 3, Beograd 11000",
    "lat": 44.818262,
    "lng": 20.45454,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf46edfa4d42f4c45",
    "tags": []
  },
  {
    "id": "predji-preko",
    "name": "Pređi preko",
    "category": "jelo",
    "area": "Borča",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-07-05",
    "price": "",
    "address": "Lazara Dokica 97, Borča",
    "lat": 44.852011,
    "lng": 20.421186,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xf298e5665ec7519",
    "tags": []
  },
  {
    "id": "bunny-cafe-belgrade",
    "name": "Bunny cafe Belgrade",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-18",
    "price": "",
    "address": "Skenderbegova 53b, Beograd",
    "lat": 44.821325,
    "lng": 20.465787,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xfc68bbab9165804a",
    "tags": []
  },
  {
    "id": "che-gusto-beograd",
    "name": "Che Gusto - Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-13",
    "price": "",
    "address": "Omladinskih brigada 90D, Beograd 11070",
    "lat": 44.813146,
    "lng": 20.395629,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1dbe2e2bce41703c",
    "tags": []
  },
  {
    "id": "reka",
    "name": "Reka",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-13",
    "price": "",
    "address": "Kej Oslobođenja 73b, Beograd",
    "lat": 44.849175,
    "lng": 20.41131,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe6df800114d2c616",
    "tags": []
  },
  {
    "id": "alisa",
    "name": "Alisa",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-05",
    "price": "",
    "address": "Kralja Milutina 35, Beograd",
    "lat": 44.803867,
    "lng": 20.46622,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8d295946b169cc68",
    "tags": []
  },
  {
    "id": "noble-roots-cocktail-bar",
    "name": "Noble Roots Cocktail Bar",
    "category": "pice",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-05",
    "price": "€€€",
    "address": "Dositejeva 7, Beograd 11000",
    "lat": 44.817319,
    "lng": 20.460977,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x67a87d42d8172f82",
    "tags": []
  },
  {
    "id": "smokvica-jovanova",
    "name": "Smokvica Jovanova",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-03",
    "price": "",
    "address": "Gospodar Jovanova 45a, 11000, Beograd",
    "lat": 44.820977,
    "lng": 20.461002,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9d5855fae724b2b0",
    "tags": []
  },
  {
    "id": "pizzeria-trg",
    "name": "Pizzeria Trg",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-02",
    "price": "",
    "address": "Makedonska 5, Beograd 11103",
    "lat": 44.815894,
    "lng": 20.461762,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc9d60d11d23da373",
    "tags": []
  },
  {
    "id": "botako-restoran-dorcol-picerija-dostava",
    "name": "Botako Restoran Dorćol | Picerija & Dostava",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-06-02",
    "price": "€€",
    "address": "Šantićeva 8, Beograd 11000",
    "lat": 44.819077,
    "lng": 20.471077,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb895fe5e8be2220",
    "tags": []
  },
  {
    "id": "basic-coffee-breakfast",
    "name": "BASIC coffee & breakfast",
    "category": "kafa",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-30",
    "price": "€",
    "address": "Admirala Geprata 10, Beograd 11000",
    "lat": 44.80796,
    "lng": 20.460005,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x53f8f95af636cb95",
    "tags": [
      "brunch"
    ]
  },
  {
    "id": "polapola-bar",
    "name": "PolaPola Bar",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-28",
    "price": "",
    "address": "Žorža Klemansoa 29b, Beograd",
    "lat": 44.825283,
    "lng": 20.470529,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x517b6ac78e5cd8dc",
    "tags": []
  },
  {
    "id": "fenisa",
    "name": "Fenisa",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-26",
    "price": "€",
    "address": "Kneginje Zorke 8, Beograd 11000",
    "lat": 44.800064,
    "lng": 20.466792,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb91dba5c37c0b510",
    "tags": []
  },
  {
    "id": "mali-prag",
    "name": "Mali prag",
    "category": "pice",
    "area": "Centar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-17",
    "price": "€",
    "address": "Kraljice Natalije 50, Beograd 11000",
    "lat": 44.810887,
    "lng": 20.459401,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe82eade193631bbd",
    "tags": []
  },
  {
    "id": "the-view-rooftop",
    "name": "The View Rooftop",
    "category": "pice",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "",
    "address": "Internacionalnih brigada 9, Beograd 11000",
    "lat": 44.795454,
    "lng": 20.467577,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa55538a8a98057e7",
    "tags": []
  },
  {
    "id": "trandafilovic",
    "name": "Trandafilović",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "",
    "address": "Makenzijeva 73, Beograd 11000",
    "lat": 44.798998,
    "lng": 20.472815,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xc83e87b7b2731d9e",
    "tags": []
  },
  {
    "id": "diner-bros-novi-beograd",
    "name": "Diner Bros. Novi Beograd",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-07",
    "price": "€€",
    "address": "Jurija Gagarina 19, Beograd 11073",
    "lat": 44.803466,
    "lng": 20.409728,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5e0db7008862122e",
    "tags": []
  },
  {
    "id": "rocket-coffee",
    "name": "Rocket Coffee",
    "category": "kafa",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-06",
    "price": "",
    "address": "Karađorđeva 49, Beograd 11000",
    "lat": 44.814197,
    "lng": 20.451717,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5ed8d12ad5c3b1d6",
    "tags": []
  },
  {
    "id": "kissa10",
    "name": "Kissa10",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-05-04",
    "price": "€€",
    "address": "Dobračina 29, Beograd",
    "lat": 44.819894,
    "lng": 20.462942,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x7830b4c2b850371a",
    "tags": []
  },
  {
    "id": "3d-board-game-pub",
    "name": "3D Board Game Pub",
    "category": "radi",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-27",
    "price": "",
    "address": "Palmira Toljatija 5, Beograd 11000",
    "lat": 44.829336,
    "lng": 20.411956,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb20cf7411ad16c03",
    "tags": []
  },
  {
    "id": "pinecone-bar-theater",
    "name": "Pinecone Bar & Theater",
    "category": "noc",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-27",
    "price": "€€",
    "address": "Vladete Jerotića 5, Beograd 11101",
    "lat": 44.814995,
    "lng": 20.471743,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x30a8bb16f98563a5",
    "tags": []
  },
  {
    "id": "di-napoli-pizzeria-restaurant",
    "name": "Di Napoli - Pizzeria Restaurant",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-23",
    "price": "",
    "address": "Bulevar Zorana Đinđića 12E, Beograd 11070",
    "lat": 44.81303,
    "lng": 20.428896,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xb97671acd4608ea2",
    "tags": []
  },
  {
    "id": "gelato-bar",
    "name": "Gelato Bar",
    "category": "kafa",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-22",
    "price": "",
    "address": "Jurija Gagarina 28, Beograd",
    "lat": 44.803963,
    "lng": 20.388352,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xbabfe587daf2e5e0",
    "tags": []
  },
  {
    "id": "helga-s-pub-mesi-mesi",
    "name": "Helga's Pub Mesi Mesi",
    "category": "pice",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-22",
    "price": "",
    "address": "Jurija Gagarina 28a, Beograd 11070",
    "lat": 44.803923,
    "lng": 20.388201,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x434e4511a5dc9283",
    "tags": []
  },
  {
    "id": "vukov-bozicni-kutak",
    "name": "Vukov Božićni kutak",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-17",
    "price": "€",
    "address": "Nikole Spasića 2a, Beograd",
    "lat": 44.818632,
    "lng": 20.454694,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xadc1fb6a13f02a3f",
    "tags": []
  },
  {
    "id": "billys-pizza-tavern-dorcol",
    "name": "Billy’s Pizza Tavern Dorćol",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-17",
    "price": "€€",
    "address": "Gospodar Jovanova 56, Beograd",
    "lat": 44.819253,
    "lng": 20.463513,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x5b6e8891cb42fbad",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "museum-of-contemporary-art",
    "name": "Museum of contemporary art",
    "category": "vidi",
    "area": "Savamala",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-12",
    "price": "",
    "address": "Ušće 10, block 15, 11070, Ušće 10, Beograd",
    "lat": 44.819584,
    "lng": 20.442477,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xd676a195f8f19372",
    "tags": []
  },
  {
    "id": "dusha-specialty-coffee",
    "name": "Dusha Specialty Coffee",
    "category": "kafa",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Mileševska 25, Beograd 11000",
    "lat": 44.800418,
    "lng": 20.479718,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x38464e285d0ae9cb",
    "tags": []
  },
  {
    "id": "kafe-kafe-bistro",
    "name": "Kafe Kafe bistro",
    "category": "kafa",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Magistratski trg 8, Beograd",
    "lat": 44.844471,
    "lng": 20.413581,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x9a44cc79fb7a7a4e",
    "tags": []
  },
  {
    "id": "zavicaj-skadarlija",
    "name": "Zavičaj Skadarlija",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "€€",
    "address": "Skadarska 18, Beograd 11000",
    "lat": 44.816734,
    "lng": 20.463733,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x33a2bfb2fd6707f0",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "june-cafe",
    "name": "June Cafe",
    "category": "kafa",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Gospodar-Jevremova 25, Beograd 11158",
    "lat": 44.820874,
    "lng": 20.459385,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xa89e6e20f227f8e1",
    "tags": []
  },
  {
    "id": "restaurant-idol",
    "name": "Restaurant IDOL",
    "category": "jelo",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "",
    "address": "Strahinjića Bana 61, Beograd 11000",
    "lat": 44.820714,
    "lng": 20.463301,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0xe58e9b571b7d77c2",
    "tags": []
  },
  {
    "id": "beograd-na-vatri",
    "name": "Beograd na vatri",
    "category": "jelo",
    "area": "Zemun",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-09",
    "price": "€€",
    "address": "Tošin bunar 148, Beograd 11070",
    "lat": 44.830377,
    "lng": 20.398892,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x8745893377bf2478",
    "tags": [
      "ručak"
    ]
  },
  {
    "id": "restoran-mokum",
    "name": "Restoran Mokum",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2025-04-04",
    "price": "",
    "address": "Jug Bogdanova 10, Beograd 11000",
    "lat": 44.814176,
    "lng": 20.455662,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x1474ee1645df3030",
    "tags": []
  },
  {
    "id": "kafana-5-glava",
    "name": "Kafana \"5 Glava\"",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-09-20",
    "price": "",
    "address": "Cetinjska 15, Beograd",
    "lat": 44.817831,
    "lng": 20.466155,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x171ea528093ec168",
    "tags": [
      "večera"
    ]
  },
  {
    "id": "klub-za-drustvene-igre-groot",
    "name": "Klub za drustvene igre - \"Groot\"",
    "category": "radi",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-07-03",
    "price": "",
    "address": "Narodnih heroja 7, Beograd 11070",
    "lat": 44.824438,
    "lng": 20.409053,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x23ccb9153efafb7e",
    "tags": []
  },
  {
    "id": "lenja-buba",
    "name": "Lenja Buba",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-02-04",
    "price": "",
    "address": "Žorža Klemansoa 19, Beograd 11000",
    "lat": 44.82215,
    "lng": 20.469172,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x40e8e944b95ea12a",
    "tags": []
  },
  {
    "id": "iva-new-balkan-cuisine",
    "name": "Iva New Balkan Cuisine",
    "category": "jelo",
    "area": "Vračar",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2024-02-04",
    "price": "",
    "address": "Svetog Save 14, Beograd 11000",
    "lat": 44.801004,
    "lng": 20.467093,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6b150ae0b675f8cb",
    "tags": []
  },
  {
    "id": "restoran-radnicki",
    "name": "Restoran Radnicki",
    "category": "jelo",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-05-21",
    "price": "",
    "address": "Tošin bunar 190, Beograd",
    "lat": 44.824571,
    "lng": 20.395608,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x155b6fe4447dc898",
    "tags": []
  },
  {
    "id": "barrel-house",
    "name": "Barrel House",
    "category": "pice",
    "area": "Dorćol",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-04-09",
    "price": "",
    "address": "Žorža Klemansoa 19, Beograd 11000",
    "lat": 44.82208,
    "lng": 20.469105,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x3688917e4e981e5d",
    "tags": []
  },
  {
    "id": "mmr-escape-rooms-lokacija-2",
    "name": "MMR Escape Rooms: Lokacija 2",
    "category": "radi",
    "area": "Novi Beograd",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2023-03-22",
    "price": "",
    "address": "Milutina Milankovića 98, Beograd 11000",
    "lat": 44.811318,
    "lng": 20.415101,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x6c69879dbcf6ce21",
    "tags": []
  },
  {
    "id": "smash-burgers",
    "name": "SMASH BURGERS",
    "category": "jelo",
    "area": "Skadarlija",
    "image": "",
    "short": "",
    "description": "",
    "rating": 5,
    "date": "2022-12-04",
    "price": "",
    "address": "Takovska 50, Beograd",
    "lat": 44.81489,
    "lng": 20.475084,
    "mapsUrl": "https://www.google.com/maps/place//data=!4m2!3m1!1s0x0:0x42011dc251b8c555",
    "tags": []
  },
  {
    "id": "narodno-pozoriste",
    "name": "Narodno pozorište",
    "category": "radi",
    "area": "Stari grad",
    "image": "",
    "short": "Opera, balet i drama u najlepšoj pozorišnoj zgradi u gradu, na Trgu republike.",
    "description": "Najstarije i najveće pozorište u Srbiji. Program se smenjuje između opere, baleta i drame. Za balet ili operu nije potrebno znanje srpskog, pa je ovo odličan izbor i za goste iz inostranstva.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Francuska 3, Beograd",
    "lat": 44.8166,
    "lng": 20.4602,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "opera",
      "balet"
    ],
    "icon": "🎭",
    "short_en": "Opera, ballet and drama in the city's most beautiful theatre building, on Republic Square.",
    "description_en": "Serbia's oldest and largest theatre. The programme alternates between opera, ballet and drama. Ballet and opera need no Serbian, so it's a great choice for visitors too."
  },
  {
    "id": "atelje-212",
    "name": "Atelje 212",
    "category": "radi",
    "area": "Centar",
    "image": "",
    "short": "Savremena drama u kultnom pozorištu u Svetogorskoj ulici.",
    "description": "Pozorište koje je od šezdesetih poznato po hrabrom i savremenom repertoaru. Posle predstave Svetogorska je puna barova za piće.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Svetogorska 21, Beograd",
    "lat": 44.8125,
    "lng": 20.4718,
    "mapsUrl": "",
    "tags": [
      "pozorište",
      "drama"
    ],
    "icon": "🎭",
    "short_en": "Contemporary drama in a cult theatre on Svetogorska street.",
    "description_en": "A theatre known since the sixties for bold, contemporary plays. After the show, Svetogorska street is full of bars for a drink."
  },
  {
    "id": "jugoslovenska-kinoteka",
    "name": "Jugoslovenska kinoteka",
    "category": "radi",
    "area": "Stari grad",
    "image": "",
    "short": "Klasici svetskog filma na velikom platnu i mali muzej filma.",
    "description": "Za ljubitelje filma: retrospektive, klasici i restaurirane kopije po povoljnim cenama, u zgradi sa muzejem kinematografije.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Uzun Mirkova 1, Beograd",
    "lat": 44.818,
    "lng": 20.4555,
    "mapsUrl": "",
    "tags": [
      "film",
      "bioskop"
    ],
    "icon": "🎬",
    "short_en": "World film classics on the big screen and a small film museum.",
    "description_en": "For film lovers: retrospectives, classics and restored prints at low prices, in a building with a cinema museum."
  },
  {
    "id": "krstarenje-rekom",
    "name": "Krstarenje Savom i Dunavom",
    "category": "radi",
    "area": "Savamala",
    "image": "",
    "short": "Sat vremena na reci uz najlepši pogled na tvrđavu i ušće.",
    "description": "Brodići kreću sa pristaništa u Savamali i plove oko Velikog ratnog ostrva i ispod tvrđave. Najlepše je pred zalazak sunca.",
    "rating": null,
    "source": "predlog",
    "price": "€€",
    "address": "Pristanište, Karađorđeva, Beograd",
    "lat": 44.8172,
    "lng": 20.4489,
    "mapsUrl": "",
    "tags": [
      "reka",
      "zalazak"
    ],
    "icon": "⛴️",
    "short_en": "An hour on the river with the best view of the fortress and the confluence.",
    "description_en": "Boats leave from the Savamala pier and sail around Great War Island and under the fortress. Best just before sunset."
  },
  {
    "id": "kalemegdan",
    "name": "Kalemegdan i Beogradska tvrđava",
    "category": "vidi",
    "area": "Stari grad",
    "image": "",
    "short": "Šetnja zidinama i zalazak sunca nad ušćem Save u Dunav.",
    "description": "Srce grada: park, zidine, Pobednik i vidikovac iznad ušća. Dođi sat vremena pre zalaska sunca.",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Kalemegdan, Beograd",
    "lat": 44.8231,
    "lng": 20.4506,
    "mapsUrl": "",
    "tags": [
      "pogled",
      "zalazak",
      "besplatno"
    ],
    "icon": "🏰",
    "short_en": "A walk on the walls and sunset over the meeting of the Sava and the Danube.",
    "description_en": "The heart of the city: park, walls, the Victor monument and a viewpoint over the confluence. Come an hour before sunset."
  },
  {
    "id": "hram-svetog-save",
    "name": "Hram Svetog Save",
    "category": "vidi",
    "area": "Vračar",
    "image": "",
    "short": "Monumentalni hram, obavezno siđi u kriptu sa zlatnim mozaicima.",
    "description": "Jedan od najvećih pravoslavnih hramova na svetu. Kripta je najmirnija ujutru, a plato ispred je odličan za odmor.",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Krušedolska 2a, Beograd",
    "lat": 44.7981,
    "lng": 20.4689,
    "mapsUrl": "",
    "tags": [
      "arhitektura",
      "besplatno"
    ],
    "icon": "⛪",
    "short_en": "A monumental church; be sure to go down to the crypt with its golden mosaics.",
    "description_en": "One of the largest Orthodox churches in the world. The crypt is quietest in the morning, and the plaza in front is great for a break."
  },
  {
    "id": "muzej-nikole-tesle",
    "name": "Muzej Nikole Tesle",
    "category": "vidi",
    "area": "Vračar",
    "image": "",
    "short": "Vođene ture i demonstracija Teslinog kalema.",
    "description": "Mali muzej sa vođenim turama i živim demonstracijama. Dođi ranije jer se ture brzo popune.",
    "rating": null,
    "source": "predlog",
    "price": "€",
    "address": "Krunska 51, Beograd",
    "lat": 44.8059,
    "lng": 20.4719,
    "mapsUrl": "",
    "tags": [
      "muzej",
      "kišni dan"
    ],
    "icon": "⚡",
    "short_en": "Guided tours and a live Tesla coil demonstration.",
    "description_en": "A small museum with guided tours and live demonstrations. Come early, as tours fill up fast."
  },
  {
    "id": "gardos-kula",
    "name": "Gardoš kula",
    "category": "vidi",
    "area": "Zemun",
    "image": "",
    "short": "Kula iznad Zemuna sa pogledom na Dunav i crvene krovove.",
    "description": "Popni se uzanim zemunskim uličicama do kule. Spoji sa ručkom na zemunskom keju.",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Grobljanska, Zemun",
    "lat": 44.8481,
    "lng": 20.4097,
    "mapsUrl": "",
    "tags": [
      "pogled",
      "besplatno"
    ],
    "icon": "🏰",
    "short_en": "A tower above Zemun with views of the Danube and red rooftops.",
    "description_en": "Climb Zemun's narrow streets up to the tower. Combine it with lunch on the Zemun riverside."
  },
  {
    "id": "beogradska-burekdzinica",
    "name": "Beogradska burekdžinica",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "Burek sa sirom ili mesom i jogurt, pravi beogradski doručak.",
    "description": "",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "",
    "lat": 44.8195,
    "lng": 20.4635,
    "mapsUrl": "https://maps.app.goo.gl/zGshVhyruSaWBTN46",
    "tags": [],
    "icon": "🥐",
    "short_en": "Cheese or meat burek with a glass of yogurt, the classic Belgrade breakfast."
  },
  {
    "id": "dorcol-knez-mihailova",
    "name": "Šetnja Dorćolom do Knez Mihailove",
    "category": "vidi",
    "area": "Dorćol",
    "image": "",
    "short": "Stare ulice Dorćola, pa glavna pešačka ulica grada.",
    "description": "",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Knez Mihailova, Beograd",
    "lat": 44.8172,
    "lng": 20.457,
    "mapsUrl": "https://maps.app.goo.gl/wyaJ8i3tTvjaXHM37",
    "tags": [],
    "icon": "🚶",
    "short_en": "The old streets of Dorćol, then the city's main pedestrian street."
  },
  {
    "id": "kafeterija-magazin-1907",
    "name": "Kafeterija Magazin 1907",
    "category": "kafa",
    "area": "Stari grad",
    "image": "",
    "short": "Specialty kafa u lepo obnovljenom starom magacinu.",
    "description": "",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "",
    "lat": 44.8187,
    "lng": 20.456,
    "mapsUrl": "https://maps.app.goo.gl/SidJSqZD1PVWHx1n6",
    "tags": [],
    "icon": "☕",
    "short_en": "Specialty coffee in a beautifully restored old warehouse."
  },
  {
    "id": "smokvica-kralja-petra",
    "name": "Smokvica Kralja Petra",
    "category": "jelo",
    "area": "Stari grad",
    "image": "",
    "short": "Ručak u dvorištu, sveže i lagano.",
    "description": "",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Kralja Petra 73, Beograd",
    "lat": 44.8214,
    "lng": 20.4597,
    "mapsUrl": "https://maps.app.goo.gl/g7AbpywAguQREJp59",
    "tags": [],
    "icon": "🥗",
    "short_en": "Lunch in a leafy courtyard, fresh and light."
  },
  {
    "id": "narodni-muzej",
    "name": "Narodni muzej",
    "category": "vidi",
    "area": "Stari grad",
    "image": "",
    "short": "Najveći muzej u Srbiji, od praistorije do Renoara i Pikasa.",
    "description": "",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Trg Republike 1a, Beograd",
    "lat": 44.8164,
    "lng": 20.46,
    "mapsUrl": "https://maps.app.goo.gl/b64RRRxbAeo5PPSb8",
    "tags": [],
    "icon": "🏛️",
    "short_en": "Serbia's largest museum, from prehistory to Renoir and Picasso."
  },
  {
    "id": "skadarlija",
    "name": "Skadarlija",
    "category": "noc",
    "area": "Skadarlija",
    "image": "",
    "short": "Boemska ulica od kaldrme, kafane i starogradska muzika.",
    "description": "",
    "rating": null,
    "source": "predlog",
    "price": "",
    "address": "Skadarska, Beograd",
    "lat": 44.8178,
    "lng": 20.4664,
    "mapsUrl": "https://maps.app.goo.gl/z1hZLqpMmUEyieSw5",
    "tags": [],
    "icon": "🎻",
    "short_en": "A cobbled bohemian street with kafanas and old-town music."
  }
];
